<?php
/**
 * Extension for Simpla
 * File is autogenerated 01.10.2021 17:01:57 by CRUD
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class AuthCodes extends Simpla
{
    public function find_code($phone)
    {
        $clear_phone = $this->users->clear_phone($phone);

        $query = $this->db->placehold("
            SELECT code
            FROM __authcodes
            WHERE phone = ?
            ORDER BY id DESC
            LIMIT 1
        ", $clear_phone);
        $this->db->query($query);

        $code = $this->db->result('code');

        return $code;
    }
}