<?php
/**
 * Extension for Simpla
 * File is autogenerated 28.08.2020 17:36:53 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Changelogs extends Simpla
{
    public const TYPE_EVENT_USER_BLOCKED = 'blocked';

    public function get_types()
    {
    	$types = array(
            'period_amount' => 'Срок и сумма заказа',
            'personal' => 'Персональные данные',
            'passport' => 'Паспортные данные',
            'regaddress' => 'Адрес регистрации',
            'faktaddress' => 'Фактический адрес',
            'contacts' => 'Контактные лица',
            'workdata' => 'Данные о работе',
            'workaddress' => 'Рабочий адрес',
            'socials' => 'Социальные сети',
            'images' => 'Статус изображения',
//            'services' => 'Сервисные услуги',
            'status' => 'Статус заявки',
            'new_photo' => 'Добавлено новое фото',
            'new_card' => 'Добавлена новая карта',
//            'additional_service' => 'Доп. Услуги при пролонгации',
//            'SHKD' => 'Отключение ШКД',
//            'additional_service_repayment' => 'Доп. услуга на закрытии',
            'pause_sms_subscription' => 'Временное отключение СМС-рассылки',
            'card_change' => 'Смена карты',
            'repeat_issuance' => 'Перевыдача',
            'choose_sbp' => 'Выбор счета СБП',
//            'disable_check_reports' => 'Проверка актуальности ССП и КИ отчета для заявки',
            'graylist' => 'Подозрение в мошенничестве',
            'test_user' => 'Тестовый пользователь',
            'amount' => 'Сумма заявки',
            'blacklist' => 'Черный список',
            'blocked' => 'Блокировка',
            'edit_amount' => 'Изменение суммы',
            'installment' => 'Инстоллмент',
            'personal_agreement' => 'Персональные согласия',
            'send_sms' => 'Отправка смс',
            'status_order' => 'Статус',
            'tehotkaz' => 'Техотказ',
            'switch_on_prolongation' => 'Включение пролонгации',
            'switch_off_prolongation' => 'Отключение пролонгации'
        );
    
        return $types;
    }
    
	public function get_changelog($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __changelogs
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_changelogs($filter = array())
	{
		$id_filter = '';
        $manager_filter = '';
        $order_filter = '';
        $user_filter = '';
        $user_or_orders_filter = '';
        $type_filter = '';
        $organization_filter = '';
        $limit = 1000;
		$page = 1;
        $sort = 'cl.id DESC';
        $join = '';
        $order_join = '';
        $search_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND cl.id IN (?@)", array_map('intval', (array)$filter['id']));
            
        if (!empty($filter['manager_id']))
            $manager_filter = $this->db->placehold("AND cl.manager_id = ?", (int)$filter['id']);

        if (!empty($filter['user_id'])) {
            if (!empty($filter['filter_type']) && ($filter['filter_type'] == 'OR') && (!empty($filter['order_ids']))) {
                $user_or_orders_filter = $this->db->placehold("AND (cl.user_id = ? OR cl.order_id IN (?@))",  (int)$filter['user_id'], array_map('intval', (array)$filter['order_ids']));
            } else {
                $user_filter = $this->db->placehold("AND cl.user_id = ?", (int)$filter['user_id']);
            }
        }
        if (!empty($filter['order_id']))
            $order_filter = $this->db->placehold("AND cl.order_id = ?", (int)$filter['order_id']);

        if (!empty($filter['type'])){
            $type_filter = $this->db->placehold("AND cl.type IN (?@)", array_map('strval', (array)$filter['type']));
        }

        if (!empty($filter['organization_id'])){
            $order_join = "INNER JOIN s_orders as ord ON ord.id = cl.order_id";
            $organization_filter = $this->db->placehold("AND ord.organization_id = ?", (int)$filter['organization_id']);
        }
        
        if (!empty($filter['search']))
        {
            if (!empty($filter['search']['date']))
                $search_filter .= $this->db->placehold(' AND DATE(cl.created) = ?', date('Y-m-d', strtotime($filter['search']['date'])));
            if (!empty($filter['search']['type']))
                $search_filter .= $this->db->placehold(' AND cl.type = ?', $filter['search']['type']);
            if (!empty($filter['search']['manager']))
                $search_filter .= $this->db->placehold(' AND cl.manager_id = ?', (int)$filter['search']['manager']);
            if (!empty($filter['search']['order']))
                $search_filter .= $this->db->placehold(' AND cl.order_id = ?', (int)$filter['search']['order']);
            if (!empty($filter['search']['user']))
                $search_filter .= $this->db->placehold(' 
                    AND cl.user_id IN (
                        SELECT id 
                        FROM __users 
                        WHERE lastname LIKE "%'.$this->db->escape($filter['search']['user']).'%"
                        OR firstname LIKE "%'.$this->db->escape($filter['search']['user']).'%"
                        OR patronymic LIKE "%'.$this->db->escape($filter['search']['user']).'%"
                    )
                ');            
        }
        
        
                if (!empty($filter['search']))
        {
            if (!empty($filter['search']['order_id']))
                $search_filter .= $this->db->placehold(' AND o.id = ?', (int)$filter['search']['order_id']);
            if (!empty($filter['search']['date']))
                $search_filter .= $this->db->placehold(' AND DATE(o.date) = ?', date('Y-m-d', strtotime($filter['search']['date'])));
            if (!empty($filter['search']['amount']))
                $search_filter .= $this->db->placehold(' AND o.amount = ?', (int)$filter['search']['amount']);
            if (!empty($filter['search']['period']))
                $search_filter .= $this->db->placehold(' AND o.period = ?', (int)$filter['search']['period']);
            if (!empty($filter['search']['fio']))
            {
                $fio_filter = array();
                $expls = array_map('trim', explode(' ', $filter['search']['fio']));
                $search_filter .= $this->db->placehold(' AND (');
                foreach ($expls as $expl)
                {
                    $expl = $this->db->escape($expl);
                    $fio_filter[] = $this->db->placehold("(u.lastname LIKE '%".$expl."%' OR u.firstname LIKE '%".$expl."%' OR u.patronymic LIKE '%".$expl."%')");
                }
                $search_filter .= implode(' AND ', $fio_filter);
                $search_filter .= $this->db->placehold(')');
            }
            if (!empty($filter['search']['birth']))
                $search_filter .= $this->db->placehold(' AND DATE(u.birth) = ?', date('Y-m-d', strtotime($filter['search']['birth'])));
            if (!empty($filter['search']['phone']))
                $search_filter .= $this->db->placehold(" AND u.phone_mobile LIKE '%".$this->db->escape(str_replace(array(' ', '-', '(', ')', '+'), '', $filter['search']['phone']))."%'");
            if (!empty($filter['search']['region']))
                $search_filter .= $this->db->placehold(" AND u.Regregion LIKE '%".$this->db->escape($filter['search']['region'])."%'");
             if (!empty($filter['search']['status']))
                $search_filter .= $this->db->placehold(" AND o.1c_status LIKE '%".$this->db->escape($filter['search']['status'])."%'");
        }

        
        
        if (!empty($filter['sort']))
        {
            switch ($filter['sort']):
            
                case 'date_asc':
                    $sort = 'cl.created ASC';
                break;
            
                case 'date_desc':
                    $sort = 'cl.created DESC';
                break;
            
                case 'type_asc':
                    $sort = 'cl.type ASC';
                break;
            
                case 'type_desc':
                    $sort = 'cl.type DESC';
                break;
            
                case 'manager_asc':
                    $join = $this->db->placehold('LEFT JOIN __managers AS m ON m.id = cl.manager_id');
                    $sort = 'm.name ASC';
                break;
            
                case 'manager_desc':
                    $join = $this->db->placehold('LEFT JOIN __managers AS m ON m.id = cl.manager_id');
                    $sort = 'm.name DESC';
                break;
            
                case 'order_asc':
                    $sort = 'cl.order_id ASC';
                break;
            
                case 'order_desc':
                    $sort = 'cl.order_id DESC';
                break;
                
                case 'user_asc':
                    $join = $this->db->placehold("LEFT JOIN __users AS u ON u.id = cl.user_id");
                    $sort = 'u.lastname ASC';
                break;
            
                case 'user_desc':
                    $join = $this->db->placehold("LEFT JOIN __users AS u ON u.id = cl.user_id");
                    $sort = 'u.lastname DESC';
                break;
                
                case 'files_asc':
                    $sort = 'cl.file_id ASC';
                break;
            
                case 'files_desc':
                    $sort = 'cl.file_id DESC';
                break;            
            
            endswitch;
        }
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT *, DATE_FORMAT(cl.created, '%d.%m.%Y %H:%i:%s') as created
            FROM __changelogs AS cl
            $join
            $order_join
            WHERE 1
                $id_filter
                $manager_filter
                $order_filter
                $user_filter
                $user_or_orders_filter
                $type_filter
                $organization_filter
                $search_filter
            ORDER BY $sort
            $sql_limit
        ");
        $this->db->query($query);
        if ($results = $this->db->results())
        {
            foreach ($results as $result)
            {
                $result->new_values = @unserialize($result->new_values) ?: $result->new_values;
                $result->old_values = @unserialize($result->old_values) ?: $result->old_values;
            }
        }
//echo __FILE__.' '.__LINE__.'<br /><pre>';var_dump($query, $results);echo '</pre><hr />';        
        return $results;
	}
    
	public function count_changelogs($filter = array())
	{
        $id_filter = '';
        $manager_filter = '';
        $order_filter = '';
        $user_filter = '';
        $search_filter = '';
        $amount_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
            
        if (!empty($filter['manager_id']))
            $manager_filter = $this->db->placehold("AND manager_id = ?", (int)$filter['id']);
		
        if (!empty($filter['order_id']))
            $order_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
		
        if (!empty($filter['user_id']))
            $user_filter = $this->db->placehold("AND user_id = ?", (int)$filter['user_id']);

        if (!empty($filter['order_ids']))
            $order_filter = $this->db->placehold("AND order_id IN (?@)", array_map('intval', $filter['order_ids']));

        if (!empty($filter['amount_change'])) {
            $amount_filter = $this->db->placehold("AND INSTR(new_values, 'amount')");
            $distinct = true;
        }

        $select_type = !empty($distinct) ? 'COUNT(DISTINCT id) AS count' : 'COUNT(id) AS count';

		$query = $this->db->placehold("
            SELECT 
                $select_type
            FROM __changelogs
            WHERE 1
                $id_filter
                $manager_filter
                $order_filter
                $user_filter
                $search_filter
                $amount_filter
        "); 
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_changelog($changelog)
    {
		$query = $this->db->placehold("
            INSERT INTO __changelogs SET ?%
        ", (array)$changelog);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_changelog($id, $changelog)
    {
		$query = $this->db->placehold("
            UPDATE __changelogs SET ?% WHERE id = ?
        ", (array)$changelog, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_changelog($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __changelogs WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    /**
     * Возвращает кол-во заявок в изменениях
     * @param array $filter_data
     * @return int
     */
    public function getTotalsChanges(array $filter_data): int
    {
        $sql = "
SELECT
    COUNT(DISTINCT o.id) as total_uniq_orders
FROM
    s_changelogs ch
    LEFT JOIN s_orders o ON o.id = ch.order_id
WHERE 1=1";

        if (!empty($filter_data['new_value'])) {
            $sql .= PHP_EOL . "AND INSTR(ch.new_values, '" . trim($filter_data['new_value']) . "')";
        }

        if (!empty($filter_data['filter_date_start'])) {
            $sql .= PHP_EOL . $this->db->placehold("AND DATE(o.date) >= ?", $filter_data['filter_date_start']);
        }

        if (!empty($filter_data['filter_date_end'])) {
            $sql .= PHP_EOL . $this->db->placehold("AND DATE(o.date) <= ?", $filter_data['filter_date_end']);
        }

        if (!empty($filter_data['filter_utm_source'])) {
            $sql .= PHP_EOL . $this->db->placehold("AND o.utm_source IN ('" . implode("', '", $filter_data['filter_utm_source']) . "')");
        }

        if (!empty($filter_data['filter_client']) && $filter_data['filter_client'] !== 'ALL') {
            $filter_client = (int)($filter_data['filter_client'] === 'PK');
            $sql .= PHP_EOL . "AND o.have_close_credits = " . $filter_client;
        }

        $this->db->query($sql);

        return (int)$this->db->result('total_uniq_orders');
    }

    /**
     * Возвращает логи изменений данных клиента
     * 
     * @param int $client_id ID клиента
     * @return array
     */
    public function get_client_log(?int $client_id): array {

        $client_log = [];

        if (empty($client_id)) {
            $logs = []; 
        } else {
            $logs = $this->get_changelogs([
                "user_id" => $client_id,
                "sort" => "date_desc",
            ]); 
        }

        $config = require __DIR__ . '/changelogs/client.php';

        $managers = [];
        foreach ($this->managers->get_managers() as $m)
            $managers[$m->id] = $m;

        foreach ($logs as $logs_item) {

            $old_values = $logs_item->old_values;

            if (!is_array($old_values)) {
                $old_values = [
                    $logs_item->type => $old_values,
                ];
            }

            foreach ($old_values as $key => $value) {

                $label = $config['labels'][ $key ] ?? null;

                $client_log_key = $config['groups'][ $key ] ?? $key;

                $client_log[ $client_log_key ] = $client_log[ $client_log_key ] ?? [];

                $client_log[ $client_log_key ][ $logs_item->created ] = [
                    "label" => $label,
                    "value" => $config[ 'value_map' ][ $key ][ $value ] ?? $value,
                    "manager" => array_key_exists($logs_item->manager_id, $managers) ? $managers[$logs_item->manager_id] : ''
                ];
            }
        }

        return $client_log;
    }


    /**
     * Фильтрует логи по названиям полей
     * 
     * @param array $input Массив с логами
     * @param array $column_keys Массив с именами полей
     * @return array Отфильтрованные логи
     */
    public function filter_logs(array $input, array $column_keys)
    {
        $result = [];
        $column_keys = array_flip($column_keys);
        foreach ($input as $key => $val) {
            $result[$key] = array_intersect_key((array) $val, $column_keys);
        }
        return $result;
    }
}