<?php
/**
 * Extension for Simpla
 * File is autogenerated 18.02.2021 13:26:18 by CRUD 
 * @author Ruslan Kopyl
 */

use App\Enums\CommentBlocks;

require_once 'Simpla.php';

class Comments extends Simpla
{
	private $blocks = array(
        'order' => 'Заявка',
        'amount' => 'Срок и сумма',
        'services' => 'Услуги',
        'personal' => 'Персональные данные',
        'passport' => 'Паспортные данные',
        'files' => 'Изображения',
        'regaddress' => 'Адрес регистрации',
        'faktaddress' => 'Адрес проживания',
        'contactpersons' => 'Контактные лица',
        'work' => 'Данные о работе',
        'workaddress' => 'Рабочий адрес',
        'socials' => 'Соц.сети',
        'missing' => 'Отвалы',
        'incomingCall' => 'Входящий звонок',
        'fromtechIncomingCall' => 'Входящий звонок Fromtech AI',
        'collection' => 'Взыскание',
        'prolongation' => 'Продление',
        'complaint' =>  'Жалобы'
    );
    
    public function get_blocks()
    {
    	return $this->blocks;
    }
    
    
    public function get_comment($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __comments
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_comments($filter = array())
	{
		$id_filter = '';
		$order_id_filter = '';
		$user_id_filter = '';
		$block_filter = '';
        $keyword_filter = '';
        $exclude_block_filter = '';
        $created_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
        if (!empty($filter['user_id']))
            $user_id_filter = $this->db->placehold("AND user_id = ?", (int)$filter['user_id']);
		
        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);

        if (!empty($filter['block']))
            $block_filter = $this->db->placehold("AND block = ?", (string)$filter['block']);

        // Фильтр на исключение определенных block
        if (!empty($filter['exclude_block'])) {
            $exclude_blocks = array_map('strval', (array)$filter['exclude_block']);
            $exclude_block_filter = $this->db->placehold("AND block NOT IN (?@)", $exclude_blocks);
        }

        if (!empty($filter['created'])){
            $startOfDay = date('Y-m-d 00:00:00', strtotime($filter['created']));
            $endOfDay = date('Y-m-d 23:59:59', strtotime($filter['created']));
            $created_filter = $this->db->placehold("AND created BETWEEN ? AND ?", $startOfDay, $endOfDay);
        }

        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT 
                c.*,
                m.name as manager_name
            FROM s_comments c
            LEFT JOIN __managers m ON c.manager_id = m.id
            WHERE 1
                $id_filter
        		$order_id_filter
        		$user_id_filter 
                $keyword_filter
                $block_filter
                $exclude_block_filter
                $created_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        
        $this->db->query($query);
        
        return $this->db->results();
	}
    
	public function count_comments($filter = array())
	{
        $id_filter = '';
		$order_id_filter = '';
		$user_id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if (!empty($filter['user_id']))
            $user_id_filter = $this->db->placehold("AND user_id = ?", (int)$filter['user_id']);
		
        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __comments
            WHERE 1
                $id_filter
        		$order_id_filter
        		$user_id_filter 
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_comment($comment)
    {
		$query = $this->db->placehold("
            INSERT INTO __comments SET ?%
        ", (array)$comment);
        $this->db->query($query);
        $id = $this->db->insert_id();
        return $id;
    }
    
    public function update_comment($id, $comment)
    {
		$query = $this->db->placehold("
            UPDATE __comments SET ?% WHERE id = ?
        ", (array)$comment, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_comment($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __comments WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    public function add_action_log($user_id, $manager_id, $action, $order_id = '')
    {
        if ($action == 'block')
            $text = 'Блокировка/удаление личного кабинета';
        elseif ($action == 'unblock')
            $text = 'Снятие блокировки/удаления';

        if (!$text)
            return;

        $block = 'order';
        $this->add_comment_log($user_id, $manager_id, $block, $text, $order_id);
    }

    public function add_field_log($user_id, $manager_id, $field_name, $old_value, $new_value, $block = 'personal', $order_id = '')
    {
        $text = "Смена " . $field_name . " с " . $old_value . " на " . $new_value;
        $this->add_comment_log($user_id, $manager_id, $block, $text, $order_id);
    }

    private function add_comment_log($user_id, $manager_id, $block, $text, $order_id = '')
    {
        $manager_id = $manager_id ?? $this->managers::MANAGER_SYSTEM_ID;
        $comment = [
            'manager_id' => $manager_id,
            'user_id' => $user_id,
            'block' => $block,
            'text' => $text,
            'created' => date('Y-m-d H:i:s'),
            'order_id' => $order_id
        ];
        if ($this->comments->add_comment($comment))
        {
            if (!empty($order_id))
                $order = $this->orders->get_order((int)$order_id);

            $manager = $this->managers->get_manager($manager_id);
            $user = $this->users->get_user($user_id);

            $this->soap->send_comment([
                'manager' => $manager->name_1c,
                'text' => $text,
                'created' => date('Y-m-d H:i:s'),
                'number' => $order->id_1c ?? '',
                'user_uid' => empty($order) ? $user->UID : ''
            ]);
        }
    }

    public function get_comments_without_analysis($dateFrom, $dateTo)
    {
        $query = $this->db->placehold("
            SELECT 
                s_comments.id,
                s_comments.user_id,
                s_comments.block,
                s_comments.created,
                s_comments.text
            FROM s_comments
            LEFT JOIN s_comment_record_analysis ON s_comments.id = s_comment_record_analysis.comment_id
            WHERE
                    s_comments.created BETWEEN '".$dateFrom."' AND '".$dateTo."'
                AND s_comments.block IN ('".CommentBlocks::INCOMING_CALL."', '".CommentBlocks::OUTGOING_CALL."') 
                AND s_comment_record_analysis.comment_id IS NULL 
                AND s_comments.text LIKE '%\"is_sent_analysis\":false%'
            ");
        $this->db->query($query);

        return $this->db->results();
    }

    public function get_mango_comment($mangoCallId)
    {
        $query = $this->db->placehold("
            SELECT * FROM __comments
            WHERE
                block = '".CommentBlocks::OUTGOING_CALL."'
                AND text LIKE '%".$mangoCallId."%'
        ");
        $this->db->query($query);

        return $this->db->result();
    }
}