<?php
/**
 * Extension for Simpla
 * File is autogenerated 25.05.2023 13:41:30 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Contracts extends Simpla
{
    private $statuses = [
        '1' => 'Подписан',
        '2' => 'Выдан',
        '3' => 'Закрыт',
        '4' => 'Просрочен',
        '5' => '',
        '6' => '',
    ];
    
    public function create_number($order)
    {
        $organization = $this->organizations->get_organization($order->organization_id);
        $order_id = isset($order->id) ? $order->id : $order->order_id;
        $contract_number = $organization->contract_prefix.date('y', strtotime($order->date)).'-'.$order_id;
        
        return $contract_number;
    }
    
	/**
	 * Contracts::make_issuance()
	 * Переводит контракт в выданный
     * 
	 * @param integer $contract_id
	 * @param string $issuance_date Y-m-d H:i:s
	 * @return void
	 */
	public function make_issuance($contract_id, $issuance_date)
    {
        if ($contract = $this->get_contract($contract_id))
        {
            $return_date = date('Y-m-d', strtotime($issuance_date) + $contract->period * 86400);
            
            $update_contract = [
                'status' => 2,
                'issuance_date' => date('Y-m-d H:i:s', strtotime($issuance_date)),
                'return_date' => $return_date,
                'loan_body_summ' => $contract->amount,
                
            ];
            if ($contract->base_percent == 0) {
                $update_contract['base_percent'] = 1;
                $update_contract['grace_date'] = $return_date;
            }
            
            $this->update_contract($contract->id, $update_contract);
        
            //TODO: делаем документы
        }
    }
    
    public function get_contract_by_params($params)
    {
		$filter = [];
        
        if (!empty($params))
            foreach ($params as $param_key => $param_value)
                $filter[] = $this->db->placehold($param_key.' = ?', $param_value);
        $where = implode(' AND ', $filter);
        
        $query = $this->db->placehold("
            SELECT * 
            FROM __contracts
            WHERE $where
        ");
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
        
    }
    
    public function get_contract($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __contracts
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_contracts($filter = array())
	{
		$id_filter = '';
		$user_id_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));

        if (!empty($filter['user_id']))
            $id_filter = $this->db->placehold("AND user_id IN (?@)", array_map('intval', (array)$filter['user_id']));
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __contracts
            WHERE 1
                $id_filter
                $user_id_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_contracts($filter = array())
	{
        $id_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __contracts
            WHERE 1
                $id_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_contract($contract)
    {
		$query = $this->db->placehold("
            INSERT INTO __contracts SET ?%
        ", (array)$contract);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_contract($id, $contract)
    {
		$query = $this->db->placehold("
            UPDATE __contracts SET ?% WHERE id = ?
        ", (array)$contract, (int)$id);
        $this->db->query($query);

        $this->logging(__METHOD__, '', '', ['contract_id' => $id, 'data' => $contract, 'debug' => debug_backtrace(0)], 'contracts.txt');

        return $id;
    }
    
    public function delete_contract($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __contracts WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    /**
     * Получает АСП по номеру договора
     * @param string $number
     * @return false|int
     */
    public function getAspByContractNumber(string $number)
    {
        $sql = $this->db->placehold("SELECT asp, order_id FROM s_contracts WHERE number = ?", $number);
        $this->db->query($sql);
        $contract = $this->db->result();

        if (!($asp = $contract->asp)) {
            $asp = $this->orders->getAspByOrderId($contract->order_id);
        }

        return $asp;
    }

    /** Получаем сумму выдачи в определенной МКК за определенный период (s_contracts.status = 2 - выдача) */
    public function getIssuanceAmountForPeriod(string $dateStart, string $dateEnd, int $organizationId): int
    {
        $query = $this->db->placehold("
            SELECT SUM(amount) as issuance_amount
            FROM s_contracts
            WHERE organization_id = ?
                AND status = 2
                AND issuance_date >= ?
                AND issuance_date < ?
            ;
        ", $organizationId, $dateStart, $dateEnd);

        $this->db->query($query);
        return (int)$this->db->result('issuance_amount');
    }
}