<?php
/**
 * Extension for Simpla
 * File is autogenerated 11.08.2020 21:29:15 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Managers extends Simpla
{
    private $salt = '0c7540eb7e65b553ec1ba6b20de79608';

    /**
     * System менеджер
     */
    public const MANAGER_SYSTEM_ID = 50;

    /**
     * ID менеджеров с индивидуальным доступом
     */
    public const MANAGER_SMIRNOV_DV = 85;
    public const MANAGER_SHVEC_LAWYER = 374;
    public const MANAGER_SMIRNOVA_TA = 335;
    public const MANAGER_POZDNJAKOV_SV = 272;
    public const MANAGER_MIHALINA_KO = 381;
    public const MANAGER_SARAIKINA_SN = 202;

	public function get_manager($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __managers
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        return $this->db->result();
    }

    /**
     * Get manager by field
     * @param string $field
     * @param string $value
     * @return ?object
     */
    public function getManagerBy(string $field, string $value)
    {
        $query = $this->db->placehold("
            SELECT * 
            FROM __managers
            WHERE {$field} = ?
            LIMIT 1
        ", $value);
        $this->db->query($query);
        return $this->db->result();
    }

    public function get_managers($filter = array())
    {
        // Кэшируем только общий список менеджеров без фильтров, так как он часто запрашивается целиком
        if (empty($filter)) {
            return $this->caches->wrap("managers:all", 3600, function() use ($filter) {
                return $this->get_managers_internal($filter);
            });
        }

        return $this->get_managers_internal($filter);
    }

    private function get_managers_internal($filter = array())
    {
		$id_filter = '';
        $keyword_filter = '';
        $rolesFilter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (isset($filter['roles'])) {
            $rolesFilter = $this->db->placehold("AND role IN (?@)", array_map('strval', (array)$filter['roles']));
        }
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __managers
            WHERE 1
                $id_filter
 	           $keyword_filter
                $rolesFilter
            ORDER BY name ASC 
            $sql_limit
        ");
        $this->db->query($query);
        return $this->db->results();
	}

    public function getSelectedManagers($date)
    {
        $query = $this->db->placehold("
            SELECT task_date,`manager_id`
            FROM __pr_tasks
            where task_date = '$date'
            GROUP BY manager_id
        ");
        $this->db->query($query);
        return $this->db->results();
    }

    public function getCompany($managerId, ?int $organizationId = null)
    {
        $txt = "";
        $organizationFilter = '';
        if ($organizationId !== null) {
            $organizationFilter = $this->db->placehold(" AND organization_id = ?", $organizationId);
        }
        
        if (gettype($managerId) !== 'string') {
            $query = $this->db->placehold("
            SELECT company  
            FROM manager_company
            WHERE manager_id = ?" . $organizationFilter . "
            LIMIT 1
        ", $managerId);
            $txt = "company";
        } else {
            $organizationFilter = '';
            if ($organizationId !== null) {
                $organizationFilter = $this->db->placehold(" AND mc.organization_id = ?", $organizationId);
            }
            $query = $this->db->placehold("
            SELECT GROUP_CONCAT(mc.manager_id) as managers, GROUP_CONCAT(mc.company) as companies
            FROM manager_company mc
            WHERE mc.manager_id IN ($managerId)" . $organizationFilter);
        }
        $this->db->query($query);
        return $this->db->result($txt);
    }

    public function getManagerTasks($managerId)
    {
        $date = date("Y-m-d");

        $query = $this->db->placehold('
                Select phone_mobile as phone from s_pr_tasks
                left JOIN s_users on s_users.id = s_pr_tasks.user_id
                where s_pr_tasks.manager_id = "' . $managerId . '" and s_pr_tasks.task_date ="' . $date . '"
                ');

        $this->db->query($query);
        return $this->db->results('phone');
    }

    public function getDNC($filter = array())
    {
        $manager_filter = '';
        $company_filter = '';

        if (isset($filter['manager_id']))
            $manager_filter = $this->db->placehold("AND manager_id   = ?", $filter['manager_id']);

        if (isset($filter['company']))
            $company_filter = $this->db->placehold("AND company   = ?", (int)$filter['company']);

        $query = $this->db->placehold('
            SELECT dnc_number  
            FROM manager_company
             where 1 '.
            $manager_filter.' '.
            $company_filter
        );
        $this->db->query($query);
        return $this->db->result('dnc_number');
    }

    public function count_managers($filter = array())
	{
        $id_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __managers
            WHERE 1
                $id_filter
                $keyword_filter
        ");
        $this->db->query($query);
        return $this->db->result('count');
    }
    
    public function add_manager($manager)
    {
		$manager = (array)$manager;
        
        if (!empty($manager['password']))
            $manager['password'] = $this->hash_password($manager['password']);
            
		$query = $this->db->placehold("
            INSERT INTO __managers SET ?%
        ", (array)$manager);
        $this->db->query($query);
        return $this->db->insert_id();
    }
    
    public function update_manager($id, $manager)
    {
		$manager = (array)$manager;
        
        if (!empty($manager['password']))
            $manager['password'] = $this->hash_password($manager['password']);
        
        $query = $this->db->placehold("
            UPDATE __managers SET ?% WHERE id = ?
        ", (array)$manager, (int)$id);
        $this->db->query($query);
        return $id;
    }
    
    public function delete_manager($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __managers WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    /**
     * @return string[]
     */
    public function get_roles(): array
    {
        return [
            'developer' => 'Разработчик',
            'admin' => 'Ст. менеджер',
            'user' => 'Менеджер',
            'verificator' => 'Верификатор',
            'verificator_minus' => 'Верификатор-',
            'edit_verificator' => 'Верификатор с расширенными правами',
            'chief_verificator' => 'Шеф-Верификатор',
            'analitic' => 'Аналитик',
            'junior_analitic' => 'Младший аналитик',
            'contact_center' => 'Исходящий КЦ',
            'contact_center_robo' => 'Исходящий КЦ робокампания',
            'contact_center_new' => 'Исходящий КЦ 1-2 день',
            'contact_center_new_robo' => 'Исходящий КЦ робокомпания 1-2 день',
            'contact_center_plus' => 'Исходящий КЦ с расширенными правами',
            'sotrudnik_cc' => 'Сотрудник КЦ',
            'verificator_cc' => 'Верификатор КЦ',
            'yurist' => 'Юрист',
            'chief_cc' => 'Нач. отдела по претензионной работе',
            'individuals' => 'Инд. рассмотрение',
            'boss_cc' => 'Руководитель КЦ',
            'accountant' => 'Бухгалтер',
            'discharge' => 'Выгрузка',
            'robot_minus'=>'Робот для минусовых дней',
            'ip_verificator' => 'ИП Верификатор', // Заявка от ИП и ООО
            'partner_specialist' => 'Работа с партнёрами',
            'declined_traffic' => 'Работа с настройками отказного трафика',
            'opr' => 'Сотрудник ОПР',
            'ts_operator' => 'Оператор ТП',
        ];
    }

    /**
     * Получение списка доступных разрешений для роли
     *
     * @param string $role
     * @return array
     * @throws Exception
     */
    public function get_permissions($role)
    {
        $access_permissions = $this->caches->wrap("permissions:{$role}", 3600, function() use ($role) {
            $roles = $this->get_roles();

            if (!isset($roles[$role])) {
                throw new Exception('Неизвестная роль пользователя: ' . $role);
            }

        $list_permissions = [
            'client_cession_info' => ['developer'], // доступ к блокам настроек цессии и агентов
            'managers' => ['developer', 'ts_operator'], // просмотр менеджеров
            'cession' => ['developer', 'ts_operator'], // доступ к цессии
            'verificators' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'], // просмотр менеджеров
            'create_managers' => ['developer', 'ts_operator'], // создание и редактирование менеджеров
            'change_card' => ['developer', 'admin', 'chief_verificator', 'chief_cc', 'verificator', 'edit_verificator', 'verificator_cc', 'contact_center_plus', 'ip_verificator', 'opr', 'ts_operator'],
            'orders' => ['developer', 'admin', 'user', 'verificator', 'verificator_minus', 'edit_verificator', 'analitic', 'verificator_cc', 'chief_verificator', 'chief_cc', 'boss_cc', 'yurist', 'ip_verificator', 'opr', 'ts_operator'], // заявки без тех отказа
            'all_orders' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'], // все заявки
            'my_orders' => ['developer', 'user', 'verificator', 'verificator_minus', 'edit_verificator', 'verificator_cc', 'chief_verificator', 'ip_verificator', 'ts_operator'], // все заявки
            'clients' => ['developer', 'admin', 'user', 'verificator', 'verificator_minus', 'edit_verificator', 'verificator_cc', 'chief_verificator', 'contact_center','contact_center_new','contact_center_new_robo', 'contact_center_plus', 'chief_cc', 'boss_cc', 'yurist', 'ip_verificator', 'opr', 'ts_operator'], // клиенты
            'logs' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'verificator_minus', 'opr', 'ts_operator'], // логи
            'settings' => ['developer', 'admin', 'opr', 'ts_operator'], // настройки
            'plan_settings' => ['developer', 'admin', 'chief_verificator', 'boss_cc', 'ip_verificator', 'opr', 'ts_operator'], // настройки
            'threshold_settings' => ['developer', 'admin', 'accountant', 'analitic', 'opr', 'ts_operator'], // настройки порогов
            'messages' => ['developer', 'admin', 'opr', 'ts_operator'], // сообщения
            'missings' => ['developer', 'admin', 'analitic', 'chief_verificator','edit_verificator', 'contact_center','contact_center_new','contact_center_new_robo','contact_center_robo', 'contact_center_plus', 'boss_cc', 'opr', 'ts_operator'], // отвалы клиентов
            'exitpools' => ['developer', 'admin', 'analitic', 'chief_verificator', 'yurist', 'boss_cc', 'contact_center','contact_center_robo', 'contact_center_new','contact_center_new_robo','contact_center_plus', 'ip_verificator', 'opr', 'ts_operator'], // опросы клиентов
            'order_time_report' => ['developer', 'admin', 'analitic', 'chief_verificator', 'boss_cc', 'contact_center', 'contact_center_new','contact_center_new_robo','contact_center_robo','contact_center_plus', 'ip_verificator', 'opr', 'ts_operator'], // опросы клиентов
            'marketing_analyst' => ['developer', 'admin', 'analitic', 'chief_verificator', 'contact_center','contact_center_new','contact_center_robo','contact_center_new_robo', 'contact_center_plus', 'ip_verificator', 'opr', 'ts_operator'], // Аналитика маркетологу
            'boss_cc' => ['developer', 'admin', 'boss_cc', 'opr', 'ts_operator'],
            'marketing_analyst_junior' => ['developer', 'admin', 'junior_analitic', 'analitic', 'contact_center','contact_center_new','contact_center_robo', 'contact_center_new_robo','contact_center_plus', 'opr', 'ts_operator'], // Аналитика маркетологу
            'verification' => ['developer', 'admin', 'verificator', 'edit_verificator', 'verificator_cc', 'chief_verificator', 'yurist', 'ip_verificator', 'opr', 'ts_operator'], // статистика верификаторов
            'cc_tasks' => ['developer', 'admin', 'contact_center', 'chief_verificator', 'contact_center_new','contact_center_new_robo','contact_center_plus','contact_center_robo', 'chief_cc', 'boss_cc', 'yurist', 'opr', 'ts_operator'],
            'tickets' => ['developer', 'admin', 'chief_cc', 'yurist', 'chief_verificator', 'opr', 'ts_operator'],
            'ticket_settings' => ['developer', 'admin', 'chief_cc', 'opr', 'ts_operator'],
            'my_tickets' => ['sotrudnik_cc', 'yurist', 'chief_verificator'],
            'ccmytascks' => ['developer', 'admin', 'verificator', 'edit_verificator', 'verificator_cc', 'chief_verificator', 'yurist', 'ip_verificator', 'opr', 'ts_operator'],
            'tickets_guide' => ['developer', 'admin', 'verificator', 'chief_verificator', 'edit_verificator', 'verificator_cc', 'chief_verificator', 'yurist', 'ip_verificator', 'opr', 'ts_operator'],
            'eventlogs' => ['developer', 'contact_center','contact_center_new','contact_center_new_robo', 'contact_center_robo','verificator', 'admin', 'chief_cc', 'chief_verificator', 'analitic', 'edit_verificator', '', 'boss_cc', 'contact_center_plus', 'yurist', 'accountant', 'junior_analitic', 'discharge', 'ip_verificator', 'opr', 'ts_operator'],
            'individual_orders' => ['developer', 'admin', 'individuals', 'opr', 'ts_operator'],
            'verificator_cc' => ['developer', 'admin', 'verificator_cc', 'yurist', 'opr', 'ts_operator'],
            'chief_verificator' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'],
            'not_received' => ['developer', 'admin', 'contact_center', 'contact_center_new','contact_center_new_robo','contact_center_plus','contact_center_robo', 'chief_cc', 'boss_cc', 'yurist', 'opr', 'ts_operator'],
            'calls_report' => ['developer', 'admin', 'boss_cc', 'opr', 'ts_operator'],
            'sms_templates' => ['developer', 'admin', 'boss_cc', 'chief_cc', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'],
            'credit_doctor_orders' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'],
            'looker_link' => ['developer', 'admin', 'analitic', 'chief_verificator', 'chief_cc', 'boss_cc', 'contact_center','contact_center_new','contact_center_new_robo','contact_center_robo', 'contact_center_plus', 'user', 'verificator', 'edit_verificator', 'ip_verificator', 'opr', 'ts_operator'],
            'insures' => ['developer', 'admin', 'chief_verificator', 'yurist', 'contact_center_plus', 'ip_verificator', 'opr', 'ts_operator'],
            'blacklist' => ['developer', 'admin', 'chief_verificator', 'ip_verificator', 'opr', 'ts_operator'],
            'promocodes' => ['developer', 'junior_analitic', 'admin', 'opr', 'ts_operator'],
            'portfolio_report' => ['developer', 'admin', 'opr', 'ts_operator'],
            'discharges_reports' => ['discharge', 'partner_specialist'],
            'autodebit' => ['developer', 'admin', 'opr', 'ts_operator'],
            'nbki_reports' => ['developer', 'admin', 'opr', 'ts_operator'],
            'installment' => ['developer', 'admin', 'opr', 'ts_operator', 'ts_operator'], // доступ к редактированию интоллмент займов
            'collection_sms_settings' => ['developer', 'admin', 'opr', 'ts_operator'], //  настройки ручных смс взыскания
            'company_orders' => ['developer', 'admin', 'ip_verificator', 'opr', 'ts_operator'], // Заявки ИП и ООО
            'reports' => ['developer', 'admin', 'edit_verificator', 'analitic', 'chief_verificator', 'chief_cc', 'boss_cc', 'yurist', 'ip_verificator', 'opr', 'ts_operator'],// отчеты
            'pdn_report' => ['developer', 'admin', 'analitic', 'opr', 'ts_operator'], // ПДН
            'declined_traffic_settings' => ['developer', 'admin', 'declined_traffic', 'opr', 'ts_operator'], // настройки продаж отказного трафика
            'export_photos'  => ['developer', 'partner_specialist', 'ts_operator'],
            'vsev_debt' => ['developer', 'admin', 'ts_operator'],
            'cb_requests' => ['developer', 'admin', 'opr', 'ts_operator', 'sotrudnik_cc', 'chief_verificator'], // запросы в ЦБ
        ];

        $access_permissions = array();
        foreach ($list_permissions  as $permission => $permission_roles)
            if (in_array($role, $permission_roles)) {
                $access_permissions[] = $permission;
            }

            return $access_permissions;
        });

        // Проверка специальных разрешений выполняется ВНЕ кеша для каждого менеджера
        $current_manager_id = $this->get_current_manager_id();
        if ($current_manager_id !== null) {
            if ($this->has_special_permission($current_manager_id, 'cession') && !in_array('cession', $access_permissions)) {
                $access_permissions[] = 'cession';
            }
            if ($this->has_special_permission($current_manager_id, 'client_cession_info') && !in_array('client_cession_info', $access_permissions)) {
                $access_permissions[] = 'client_cession_info';
            }
        }

        return $access_permissions;
    }

    /**
     * Проверка специальных разрешений для конкретных менеджеров
     * @param int $manager_id
     * @param string $permission
     * @return bool
     */
    private function has_special_permission(int $manager_id, string $permission): bool
    {
        $special_permissions = [
            'cession' => [self::MANAGER_POZDNJAKOV_SV],
            'client_cession_info' => [
                self::MANAGER_SMIRNOV_DV,
                self::MANAGER_SHVEC_LAWYER,
                self::MANAGER_SMIRNOVA_TA,
                self::MANAGER_POZDNJAKOV_SV,
                self::MANAGER_SMIRNOVA_TA,
                self::MANAGER_SARAIKINA_SN,
            ]
        ];
        
        return isset($special_permissions[$permission]) && 
               in_array($manager_id, $special_permissions[$permission]);
    }

    /**
     * Получение ID текущего менеджера
     * @return int|null
     */
    private function get_current_manager_id(): ?int
    {
        if (isset($_SESSION['manager_id'])) {
            return (int)$_SESSION['manager_id'];
        }
        return null;
    }

    /**
     * Получение страницы после входа
     * @param $role string
     * @return string
     */
    public function get_after_login_page($role)
    {
        $pages = [
            'partner_specialist' => 'arbitration_agreements_generator'
        ];

        return $pages[$role] ?? $this->config->root_url;
    }

    public function check_password($login, $password)
    {
        $password = $this->hash_password($password);
    	$query = $this->db->placehold("
            SELECT id 
            FROM __managers 
            WHERE login = ?
            AND password = ?
        ", $login, $password);
        $this->db->query($query);
        return $this->db->result('id');        
    }

    /**
     * @param string $password
     * @return string
     */
    private function hash_password(string $password): string
    {
        return md5(sha1($this->salt . $password) . $this->salt);
    }

    /**
     * Отчёт по эфеективности работников КЦ по отвалам
     * @param array $filter_data
     * @return array|false
     */
    public function getMissingsOrdersCC(array $filter_data)
    {
        $where = [];
        $where_phone = [];
        $filter_duration = $filter_data['filter_duration'] ?? 30;
        $sql =
            "SELECT
                u.missing_manager_id,
                m.name_1c,
                COUNT(o.id) as total_orders,
                SUM(IF(o.have_close_credits = 0, (
                        u.personal_data_added = 1 AND DATE(u.personal_data_added_date) = DATE(o.date)
                    AND u.address_data_added = 1 AND DATE(u.additional_data_added_date) = DATE(o.date)
                    AND u.accept_data_added = 1 AND DATE(u.accept_data_added_date) = DATE(o.date)
                    AND u.card_added = 1 AND DATE(u.card_added_date) = DATE(o.date)
                    AND u.files_added = 1 AND DATE(u.files_added_date) = DATE(o.date)
                    AND u.additional_data_added = 1 AND DATE(u.additional_data_added_date) = DATE(o.date)), 0)) as total_bad_orders, -- отвалы
                SUM(IF(o.confirm_date IS NULL, 0, 1)) as total_confired_orders, -- выданные займы
                SUM((
                    SELECT COUNT(DISTINCT mc.to_number) FROM s_mangocalls mc WHERE
                        mc.manager_id = u.missing_manager_id
                        AND mc.duration >= $filter_duration -- время разговора в сек.
                        AND mc.to_number = u.phone_mobile -- исходящие из КЦ клиенту
                        AND DATE(o.date) = DATE(mc.created)
                        -- {{where_phone}}
                )) as total_calls,
               SUM(
                    EXISTS(SELECT * FROM s_mangocalls mc WHERE
                        mc.manager_id = u.missing_manager_id                                     
                        AND o.confirm_date IS NOT NULL   
                        AND DATE(o.confirm_date) = DATE(mc.created)                                                         
                        AND mc.duration >= $filter_duration -- время разговора в сек.
                        AND mc.to_number = u.phone_mobile -- исходящие из КЦ клиенту
                        -- {{where_phone}}
                    )
                ) as total_orders_with_confirmed,
                SUM(
                    IF(EXISTS(SELECT * FROM s_mangocalls mc WHERE
                        mc.manager_id = u.missing_manager_id                                     
                        AND o.confirm_date IS NOT NULL   
                        AND DATE(o.confirm_date) = DATE(mc.created)                                                         
                        AND mc.duration >= $filter_duration -- время разговора в сек.
                        AND mc.to_number = u.phone_mobile -- исходящие из КЦ клиенту
                        -- {{where_phone}}
                    ), o.amount, 0)
                ) as total_amount
                FROM 
                    s_orders o
                    LEFT JOIN s_users u ON u.id = o.user_id
                    LEFT JOIN s_managers m ON m.id = u.missing_manager_id
            WHERE 1 = 1
                -- {{where}}
                GROUP BY u.missing_manager_id
        ";

        // даты заявки
        if (!empty($filter_data['filter_date_order'])) {
            $where[] = $this->db->placehold("DATE(o.date) BETWEEN DATE(?) AND DATE(?)", $filter_data['filter_date_order']['filter_date_start'], $filter_data['filter_date_order']['filter_date_end']);
            $where_phone[] = $this->db->placehold("mc.created BETWEEN ? AND ?", $filter_data['filter_date_order']['filter_date_start'], $filter_data['filter_date_order']['filter_date_end']);
        }

        // фильтр по менеджерам
        if (!empty($filter_data['filter_manager_ids'])) {
            $where[] = $this->db->placehold("u.missing_manager_id IN (?@)", $filter_data['filter_manager_ids']);
        }

        $query = strtr($sql, [
            '-- {{where_phone}}' => !empty($where_phone) ? "AND " . implode(" AND ", $where_phone) : '',
            '-- {{where}}' => !empty($where) ? "AND " . implode(" AND ", $where) : '',
        ]);
        $this->db->query($query);
        return $this->db->results();
    }

    public function get_verificators()
    {
        $query = "SELECT * FROM __managers WHERE role = 'verificator' OR role = 'edit_verificator'";
        $this->db->query($query);
        return $this->db->results();
    }

    /**
     * Проверка, может ли роль заниматься верификацией заявок
     *
     * @param string $role
     * @return bool
     */
    public function canVerify(string $role): bool
    {
        // Список ролей‑верификаторов собран в одном месте,
        // чтобы при изменениях не править проверки по всему коду
        $verificatorRoles = [
            'verificator',
            'edit_verificator',
            'verificator_minus',
        ];

        return in_array($role, $verificatorRoles, true);
    }

    public function getCompanyManagers($plus, $minus, ?int $organizationId = null)
    {
        $organizationFilter = '';
        if ($organizationId !== null) {
            $organizationFilter = $this->db->placehold(" AND manager_company.organization_id = ?", $organizationId);
        }
        
        $query = $this->db->placehold("SELECT s_managers.id, s_managers.name FROM manager_company 
                    LEFT JOIN s_managers on s_managers.id = manager_company.manager_id 
                                      where manager_company.company is not null 
                                      and manager_company.plus = ? and manager_company.minus = ?" . $organizationFilter, (bool)$plus, $minus);

        $this->db->query($query);
        return $this->db->results();
    }

    public function add_schedule($date, $managers, $plus, ?int $organizationId = null)
    {
        $organizationFilter = '';
        if ($organizationId !== null) {
            $organizationFilter = $this->db->placehold(" AND organization_id = ?", $organizationId);
        }
        
        $query = $this->db->placehold("
            DELETE FROM managers_schedule 
                   WHERE date = ?
                   AND plus = ?" . $organizationFilter, (string)$date, (bool)$plus);
        $this->db->query($query);

        foreach ($managers as $manager){
            $query = $this->db->placehold("
            INSERT INTO managers_schedule (manager_id, date, plus, organization_id)
            VALUES (?, ?, ?, ?);
        ", (int)$manager, (string)$date, (bool)$plus, $organizationId);
            $this->db->query($query);
        }
    }

    public function getScheduledManagers($date, $plus, ?int $organizationId = null)
    {
        $organizationFilter = '';
        if ($organizationId !== null) {
            $organizationFilter = $this->db->placehold(" AND managers_schedule.organization_id = ?", $organizationId);
        }
        
        $query = $this->db->placehold("SELECT s_managers.id, s_managers.name,s_managers.role FROM managers_schedule
                    LEFT JOIN s_managers on s_managers.id = managers_schedule.manager_id 
                    where managers_schedule.date = ?
                    and plus = ?" . $organizationFilter, (string) $date, (bool)$plus);
        $this->db->query($query);
        return $this->db->results();
    }

    public function update_manager_data($id, $manager)
    {
        $query = $this->db->placehold("
            UPDATE __managers SET ?% WHERE id = ?
        ", (array) $manager, (int)$id);
        $this->db->query($query);
        return $id;
    }

    public function getDeletedManager()
    {
        $query = $this->db->placehold("
            SELECT id as manager_id 
            FROM __managers
            WHERE vox_deleted = true
        ");
        $this->db->query($query);
        return $this->db->results();
    }

    /**
     * @return array|false
     */
    public function getManagers($plus, $minus, ?int $organizationId = null)
    {
        if ($plus) {
            $role = $this->db->placehold("__managers.role = 'contact_center_new' OR __managers.role = 'contact_center_new_robo'");
        }else if (!$plus && $minus === 'false'){
            $role = $this->db->placehold("__managers.role = 'contact_center' OR __managers.role = 'contact_center_robo'");
        }else if($minus) {
            $role = $this->db->placehold("__managers.role = 'robot_minus'");
        }
        $query = $this->db->placehold("
            SELECT __managers.id, __managers.name,manager_company.company,manager_company.dnc_number
            FROM __managers
            LEFT JOIN manager_company on __managers.id = manager_company.manager_id AND manager_company.organization_id <=> ?
            Where $role ORDER BY __managers.id ASC                                                          
        ", $organizationId);
        $this->db->query($query);
        return $this->db->results();
    }

    /**
     * @param int $managerId
     * @return false|int
     */
    public function getVoxManager(int $managerId, ?int $organizationId = null)
    {
        $query = $this->db->placehold("
            SELECT id, company, dnc_number 
            FROM manager_company 
            WHERE manager_id = ? 
              AND organization_id <=> ?
            LIMIT 1 
        ", $managerId, $organizationId);
        $this->db->query($query);

        return $this->db->result();
    }

    /**
     * @param array $data
     * @return mixed
     */
    public function insertVoxData(array $data, ?int $organizationId = null)
    {
        $data['organization_id'] = $organizationId;

        $query = $this->db->placehold("
            INSERT INTO manager_company SET ?%
        ", $data);
        $this->db->query($query);
        return $this->db->insert_id();
    }

    /**
     * @param int $managerId
     * @param array $data
     * @return void
     */
    public function updateVoxData(int $managerId, array $data, ?int $organizationId = null)
    {
        $query = $this->db->placehold("
            UPDATE manager_company 
            SET ?% 
            WHERE manager_id = ?
              AND organization_id <=> ?
        ", $data, $managerId, $organizationId);
        $this->db->query($query);
    }

    /**
     * Проверка онлайн статуса менеджера
     *
     * @param int $managerId ID менеджера
     * @return bool
     */
    public function isManagerOnline(int $managerId): bool
    {
        $this->db->query("
            SELECT COUNT(*) as is_online
            FROM __managers
            WHERE id = ?
            AND last_visit > DATE_SUB(NOW(), INTERVAL 5 MINUTE)
        ", $managerId);

        $result = $this->db->result();
        return $result->is_online > 0;
    }

    public function add(int $managerId)
    {
        $this->db->query($this->db->placehold('INSERT INTO __manager_visits SET ?%', [
            'manager_id' => $managerId,
            'ip' => $_SERVER['REMOTE_ADDR'],
            'date_create' => date('Y-m-d H:i:s'),
            'last_visit' => date('Y-m-d H:i:s')
        ]));
    }

    public function update(int $managerId)
    {
        $this->db->query($this->db->placehold("SELECT * FROM __manager_visits WHERE manager_id = ? AND ip = ? ORDER BY id DESC LIMIT 1", $managerId, $_SERVER['REMOTE_ADDR']));
        empty($row = $this->db->result()) ? $this->add($managerId) :  $this->db->query($this->db->placehold("UPDATE __manager_visits SET ?% WHERE id = ?", ['last_visit' => date('Y-m-d H:i:s')], $row->id));
    }
}
