<?php
/**
 * Extension for Simpla
 * File is autogenerated 05.02.2021 8:47:52 by CRUD
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class NotificationsManagers extends Simpla
{

    /**
     * Обновить статус уведомления read/unread
     * @param int $id
     * @return void
     */
    public function markNotificationAsRead(int $id)
    {
        $query = $this->db->placehold("
            UPDATE __managers_notifications SET `is_read` = 1 WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        return true;
    }

    /**
     * Отправка уведомлений
     * @param $params
     * @return void
     */
    public function sendNotification($params)
    {
        $fromUser = $params['from_user'] ?? 1;
        $toUser = $params['to_user'];
        $subject = $params['subject'];
        $message = $params['message'];
        $isRead = $params['is_read'] ?? false;

        $args = [
            "from_user" => $fromUser,
            "to_user" => $toUser,
            "subject" => $subject,
            "is_read" => $isRead,
            "created_at" => date('Y-m-d h:i:s'),
            "message" => $message,
        ];

        $query = $this->db->placehold("INSERT INTO __managers_notifications SET ?%", (array)$args);
        $this->db->query($query);
    }

    /**
     * Тестовое уведовление
     *
     * @param $dataPost
     * @return void
     */
    public function testNotification($dataPost)
    {

        $json = json_encode([
            "to_channel" => $dataPost["manager"],
            "id_message" => 0,
            "subject" => "Тикет система",
            "text" => "Тестовое уведомление!",

        ]);


        $curl = curl_init('https://service.boostra.ru/api/manager/notification/create');
        curl_setopt($curl, CURLOPT_HEADER, false);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array("Content-type: application/json", "accept:  application/json"));
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $json);

        if(curl_exec($curl) === false)
        {
            echo 'Curl error: ' . curl_error($curl);
        }
        else
        {
            echo 'Operation completed without any errors';
        }

        curl_close($curl);
    }

}