<?php
/**
 * Extension for Simpla
 * File is autogenerated 25.05.2023 13:40:41 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Operations extends Simpla
{
    public function get_operation_type_id($type)
    {
        $query = $this->db->placehold("
            SELECT id 
            FROM __operation_types
            WHERE type = ?
        ", (string)$type);
        $this->db->query($query);
        $id = $this->db->result('id');

        return $id;
    }
    
    public function get_operation_types()
    {
        $query = $this->db->placehold("
            SELECT *
            FROM __operation_types
        ");
        $this->db->query($query);
        $results = $this->db->results();

        return $results;    	
    }
    
    public function get_added_percents($contract_id)
    {
        $operation_type_id = $this->get_operation_type_id('PERCENTS');
        $query = $this->db->placehold("
            SELECT SUM(amount) AS added_percents
            FROM __operations
            WHERE contract_id = ?
            AND operation_type_id = ?
        ", (int)$contract_id, $operation_type_id);
        $this->db->query($query);
        $result = $this->db->result('added_percents');

        return (int)$result;        
    }
    
	public function get_current_operation($contract_id, $date, $operation_type_id)
	{
        $query = $this->db->placehold("
            SELECT * 
            FROM __operations
            WHERE contract_id = ?
            AND operation_date = ?
            AND operation_type_id = ?
        ", $contract_id, $date, $operation_type_id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_operation($id)
	{
        $query = $this->db->placehold("
            SELECT * 
            FROM __operations
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_operations($filter = array())
	{
		$id_filter = '';
        $order_id_filter = '';
        $contract_id_filter = '';
        $type_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id IN (?@)", array_map('intval', (array)$filter['order_id']));
		
        if (!empty($filter['contract_id']))
            $contract_id_filter = $this->db->placehold("AND contract_id IN (?@)", array_map('intval', (array)$filter['contract_id']));
		
		if (!empty($filter['type']))
            $type_filter = $this->db->placehold("AND type IN (?@)", array_map('strval', (array)$filter['type']));
        
        if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __operations
            WHERE 1
                $id_filter
                $order_id_filter
                $contract_id_filter
				$type_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_operations($filter = array())
	{
        $id_filter = '';
        $order_id_filter = '';
        $contract_id_filter = '';
        $type_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id IN (?@)", array_map('intval', (array)$filter['order_id']));
		
        if (!empty($filter['contract_id']))
            $contract_id_filter = $this->db->placehold("AND contract_id IN (?@)", array_map('intval', (array)$filter['contract_id']));
		
		if (!empty($filter['type']))
            $type_filter = $this->db->placehold("AND type IN (?@)", array_map('strval', (array)$filter['type']));
        
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __operations
            WHERE 1
                $id_filter
                $order_id_filter
                $contract_id_filter
                $type_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_operation($operation)
    {
		$query = $this->db->placehold("
            INSERT INTO __operations SET ?%
        ", (array)$operation);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_operation($id, $operation)
    {
		$query = $this->db->placehold("
            UPDATE __operations SET ?% WHERE id = ?
        ", (array)$operation, (int)$id);
        $this->db->query($query);

        return $id;
    }
    
    public function delete_operation($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __operations WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }
}