<?php
/**
 * Extension for Simpla
 * File is autogenerated 18.05.2021 10:28:50 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Sms extends Simpla
{
    /**
     * Шаблон письма сразу после одобрения
     */
    public const AUTO_APPROVE_TEMPLATE_NOW = 17;
    public const AUTO_REJECT_TEMPLATE_NOW = 28;
    public const AUTO_REJECT_TEMPLATE_SECOND = 29;
    public const AUTO_REJECT_TEMPLATE_THIRD = 30;
    public const AUTO_REJECT_TEMPLATE_FOURTH = 40;
    public const AUTO_REJECT_TEMPLATE_FIFTH = 41;
    public const AUTO_REJECT_TEMPLATE_EMERGENCY = 54;
    public const AUTO_REJECT_TEMPLATE_INVALID_PASSPORT = 55;
    public const AUTO_REJECT_TEMPLATE_EXPIRED = 56;
    public const SMS_TEMPLATE_APPROVE_OTHER = 93;


    /**
     * Шаблон СМС клиентам с мотивацией на закрытие
     */
    public const SMS_TEMPLATE_MOTIVATION_CLOSE = 19;

    /**
     * Шаблон смс для перехода в ЛК лайкзайма
     */
    public const SMS_TEMPLATE_LIKEZAIM = 37;

    public const LK_TYPE = 50;
	private $template_types = array(
        'order' => 'Заявки',
        'missing' => 'Отвалы',
        'prolongation' => 'Пролонгации',
        'quality_control' => 'Контроль качества',
        'likezaim' => 'Лайкзайм',
        'ccprolongation' => 'Взыскание',
    );
    
    public function get_template_types()
    {
        return $this->template_types;
    }
    
    public function get_template($id, $site_id = null)
	{
		$cacheKey = 'sms_template:' . (int)$id . ':' . ($site_id ?? 'null');

		return $this->caches->wrap($cacheKey, 600, function () use ($id, $site_id) {
			$query = $this->db->placehold("
				SELECT *
				FROM __sms_templates
				WHERE id = ?
			", (int)$id);
			$this->db->query($query);
			$result = $this->db->result();

			// Если указан сайт и есть поле вроде template_googlo — возвращаем именно его
			if ($site_id) {
				$property = 'template_' . $site_id;
				if (isset($result->$property) && $result->$property) {
					$result->template = $result->$property;
				}
			}

			return $result;
		});
    }
    
	public function get_templates($filter = array())
	{
		$id_filter = '';
		$type_filter = '';
        $types_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
        if (!empty($filter['type']))
            $type_filter = $this->db->placehold("AND type = ?", (string)$filter['type']);

        if (!empty($filter['types']))
            $types_filter = $this->db->placehold("AND type IN (?@)", array_map('strval', (array)$filter['types']));

		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __sms_templates
            WHERE 1
                $id_filter
                $type_filter
				$keyword_filter
                $types_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();

        if (!empty($results) && !empty($filter['site_id'])) {
            $site_id = $filter['site_id'];
            $property = 'template_' . $site_id;
            foreach ($results as &$result) {
                if (isset($result->$property) && $result->$property) {
                    $result->template = $result->$property;
                }
            }
        }
        
        return $results;
	}
    
	public function count_templates($filter = array())
	{
        $id_filter = '';
        $type_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if (!empty($filter['type']))
            $type_filter = $this->db->placehold("AND type = ?", (string)$filter['type']);
        
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __sms_templates
            WHERE 1
                $id_filter
                $type_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_template($sms_template)
    {
		$query = $this->db->placehold("
            INSERT INTO __sms_templates SET ?%
        ", (array)$sms_template);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }

    public function update_template($id, $sms_template, $site_id = null)
    {
        $sms_template = (array)$sms_template;

        if ($site_id) {
            if (isset($sms_template['template'])) {
                $property = 'template_' . $site_id;
                $sms_template[$property] = $sms_template['template'];
                unset($sms_template['template']);
            }
        }

        $query = $this->db->placehold("
            UPDATE __sms_templates SET ?% WHERE id = ?
        ", $sms_template, (int)$id);
        $this->db->query($query);

        // После обновления очистим кеш
        $this->clear_cache($id, $site_id);

        return $id;
    }

    protected function clear_cache($id, $site_id = null)
    {
        $cacheKey = 'sms_template:' . (int)$id . ':' . ($site_id ?? 'null');
        $this->caches->delete($cacheKey);
    }
    
    public function delete_template($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __sms_templates WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }


	public function get_message($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __sms_messages
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_messages($filter = array())
	{
		$id_filter = '';
        $order_id_filter = '';
        $keyword_filter = '';
        $phone_filter = '';
        $limit = 1000;
		$page = 1;
        $where = [];

        if (!empty($filter['phone'])) {
            $phone_filter = $this->db->placehold("AND phone = ?", $filter['phone']);
        }
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
		if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
        
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (!empty($filter['type'])) {
            $where[] = $this->db->placehold("type = ?", $filter['type']);
        }
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __sms_messages
            WHERE 1
                $phone_filter
                $id_filter
                $order_id_filter
				$keyword_filter
            -- {{where}}
            ORDER BY id DESC 
            $sql_limit
        ");

        $query = strtr($query, [
            '-- {{where}}' => !empty($where) ? "AND " . implode(" AND ", $where) : '',
        ]);

        $this->db->query($query);
        return $this->db->results();
	}
    
	public function count_messages($filter = array())
	{
        $id_filter = '';
        $order_id_filter = '';
        $keyword_filter = '';
        $where = [];
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
		if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
        
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (!empty($filter['type'])) {
            $where[] = $this->db->placehold("type = ?", $filter['type']);
        }

        if (isset($filter['validated'])) {
            $where[] = $this->db->placehold("validated = ?", $filter['validated']);
        }

        if (!empty($filter['created_after'])) {
            $where[] = $this->db->placehold("created > ?", $filter['created_after']);
        }

        if (!empty($filter['phone'])) {
            $where[] = $this->db->placehold("phone = ?", $filter['phone']);
        }
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __sms_messages
            WHERE 1
                $id_filter
                $order_id_filter
                $keyword_filter
            -- {{where}}
        ");

        $query = strtr($query, [
            '-- {{where}}' => !empty($where) ? "AND " . implode(" AND ", $where) : '',
        ]);

        $this->db->query($query);
        return $this->db->result('count');
    }
    
    public function add_message($sms_message)
    {
		$query = $this->db->placehold("
            INSERT INTO __sms_messages SET ?%
        ", (array)$sms_message);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_message($id, $sms_message)
    {
		$query = $this->db->placehold("
            UPDATE __sms_messages SET ?% WHERE id = ?
        ", (array)$sms_message, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_message($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __sms_messages WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    /**
     * Получает кол-во одобренных заявок для отправки смс
     * @return array|false
     */
    public function getTotalSmsApprove()
    {
        $sql = "SELECT
    COUNT(o.id) as total,
    datediff(NOW(), o.approve_date) as day_after_approve
FROM s_orders o LEFT JOIN s_users u ON u.id = o.user_id
WHERE o.status = 2 AND o.confirm_date IS NULL AND o.1c_status != '5.Выдан' AND o.1c_status != '6.Закрыт'
  AND NOT EXISTS (SELECT * FROM s_orders o2 WHERE o2.id > o.id AND o2.user_id = o.user_id)
  AND datediff(NOW(), o.approve_date) BETWEEN 1 AND 7
GROUP BY day_after_approve";

        $this->db->query($sql);
        return $this->db->results();
    }

    public function add_push($pushData)
    {
        $query = $this->db->placehold("
            INSERT INTO __pushes SET ?%
        ", (array)$pushData);
        $this->db->query($query);
        $id = $this->db->insert_id();

        return $id;
    }


    public function get_pushes_sms($filter = array())
    {
        $date_filter = '';
        $type_filter = '';
        $status_filter = '';
        if (isset($filter['date_from']) &&  isset($filter['date_to'])){
            $date_filter = $this->db->placehold("AND created between ? AND ?",  $filter['date_from'],$filter['date_to']);
        }

        if (isset($filter['type'])){
            $type_filter = $this->db->placehold("AND type = ?", $filter['type']);
        }
        if (isset($filter['status'])){
            $status_filter = $this->db->placehold("AND send_status = ?", $filter['status']);
        }
        $query = $this->db->placehold('
                Select count(id) as count, DATE(created) as created_date from '. $filter['table'].' 
                where 1 '.
            $date_filter.' '.
            $type_filter.' '.
            $status_filter.' '.
            'GROUP BY created_date'

        );
        $this->db->query($query);
        return $this->db->results();
    }

    public function get_pr_sms($period, $date)
    {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks_sms
            WHERE period IN (?@) AND date = ?
        ", $period, $date);
        $this->db->query($query);
        return  $this->db->result();


    }

    /**
     * Проверяем лимит входящих смс
     * @param $phone
     * @return bool
     */
    public function check_total_limit($phone): bool
    {
        $limit = 10;

        $query = $this->db->placehold("
        SELECT *
        FROM __sms_validate
        WHERE phone = ?
        ", (string)$phone);
        $this->db->query($query);
        $result = $this->db->result();

        return ($result->total ?? 0) >= $limit;
    }

    /**
     * Очищаем счетчик смс
     * @param $phone
     * @return void
     */
    public function delete_records_by_phone($phone)
    {
        $query = $this->db->placehold("
        DELETE FROM __sms_validate
        WHERE phone = ?
    ", $phone);
        $this->db->query($query);
    }

    /**
     * @param $phone
     * @param array $data
     * @return mixed
     */
    public function editSmsByPhone($phone, array $data)
    {
        $query = $this->db->placehold("UPDATE __sms_messages SET ?% WHERE phone = ?", $data, $phone);
        return $this->db->query($query);
    }

    /**
     * Проверка наличия отправленного SMS по типу и номеру за сегодня
     * @param string $phone Номер телефона, на который отправляется SMS.
     * @param string $type Тип SMS сообщения.
     *
     * @return bool Возвращает true, если SMS уже была отправлена сегодня, иначе false.
     */
    public function isSmsAlreadySentToday(string $phone, string $type): bool
    {
        $todayStart = date('Y-m-d 00:00:00');
        $todayEnd = date('Y-m-d 23:59:59');

        $query = $this->db->placehold("
            SELECT COUNT(*) as count
            FROM __sms_messages
            WHERE phone = ?
            AND type = ?
            AND created BETWEEN ? AND ?
            AND send_status = 'success'
        ", $phone, $type, $todayStart, $todayEnd);

        $this->db->query($query);
        $result = $this->db->result();

        return $result->count > 0;
    }
}