<?php

/**
 * Extension for Simpla
 * File is autogenerated 18.08.2020 16:00:06 by CRUD 
 * @author Alexey Zorin
 */
require_once 'Simpla.php';

use api\traits\setPages;
use api\traits\Sorts;

class TasksOverdueController extends Simpla {

    use setPages,Sorts;

    /**
     * Получаем данные о клиентах, займах и лт
     * @return type
     */
    public function getTasks() {
        $query = $this->db->placehold("
            SELECT 
                __lpt.* , 
                __users.lastname,
                __users.patronymic,
                __users.firstname,
                __users.phone_mobile,
                __users.UID,
                __user_balance.user_id,
                __user_balance.zaim_number,
                __user_balance.zaim_summ,
                __user_balance.percent,
                __user_balance.ostatok_od,
                __user_balance.ostatok_percents,
                __user_balance.ostatok_peni,
                __user_balance.zaim_date,
                __user_balance.payment_date,
                __user_balance.cc_status,
                __user_balance.last_prolongation,
                __user_balance.prolongation_count,
                __user_balance.prolongation_summ_percents,
                __user_balance.prolongation_amount,
                __user_balance.last_update 
            FROM __lpt, __user_balance, __users
            WHERE __lpt.user_balance_id = __user_balance.id
            AND __users.id = __user_balance.user_id
            AND NOT __lpt.status = 'Выход за 1-3' 
            AND NOT __lpt.status = 'Нулевой долг'
             " . $this->sortTasksOverdue()
        );
        $query .= $this->getLimit($query);
        $this->db->query($query);
        return $this->db->results();
    }

}
