<?php

/**
 * Extension for Simpla
 * File is autogenerated 16.11.2021 12:31:36 by CRUD
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

use api\traits\setPages;
use api\traits\myTasks;

class Tasks extends Simpla{

    use setPages, myTasks;

    private $pr_statuses = array(
        0 => 'Новый',
        1 => 'Перезвон',
        2 => 'Недозвон',
        3 => 'Перспектива',
        4 => 'Отказ',
        5 => 'Уже оплатил',
        6 => 'Получил информацию по долгу',
        7 => 'Подтвердил Личность',
        8 => 'Умер, тюрьма, банкрот',
        9 => 'Номер в стоп листе',
        10 => 'Негатив от абонента',
        11 => 'Контакт с третьим лицом',
        12 => 'Заявка на рефинансирование',
    );

    /**
     * Получить все задачи для определенного тикета
     */
    public function getTaskByTicketId($ticketId) {
        $query = $this->db->placehold("
            SELECT 
                * 
            FROM 
                __users,
                __orders,
                __user_balance,
                __pr_tasks
            WHERE 
                __pr_tasks.ticketId = ?
            AND
                __users.id = __pr_tasks.user_id
            AND 
                __user_balance.zaim_number = __pr_tasks.number
            AND 
                __orders.id = __pr_tasks.user_balance_id
        ", (int) $ticketId);
        $query .= $this->getLimit($query);
        $this->db->query($query);
        $result = $this->db->results();
        return $result;
    }

    /**
     * Получить все задачи менеджера по его id
     */
    public function getMyTaskByTickets($managerId) {
        $query = $this->db->placehold("
            SELECT 
                * 
            FROM 
                __managers,
                __users,
                __user_balance,
                __pr_tasks,
                __orders
            WHERE 
                __managers.id = ?
            AND
                __pr_tasks.manager_id = __managers.id
            AND
                __users.id = __pr_tasks.user_id
            AND 
                __user_balance.zaim_number = __pr_tasks.number
            AND 
                __orders.id = __pr_tasks.user_balance_id
        ", (int) $managerId);
        $query .= $this->getLimit($query);
        $this->db->query($query);
        $result = $this->db->results();
        return $result;
    }

    public function get_pr_statuses() {
        return $this->pr_statuses;
    }

    public function get_current_pr_task($number, $task_date)
    {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE number = ?
            AND task_date = ?
        ", $number, $task_date);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

    public function get_pr_task($id)
    {
        $query = $this->db->placehold("
            SELECT * 
            FROM __pr_tasks
            WHERE id = ?
        ", (int) $id);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

    public function delete_manager_tasks($managers){
        $data = date("Y-m-d");
        $arr = implode(',' ,$managers);

        $query = $this->db->placehold('DELETE FROM __pr_tasks
            WHERE task_date = "'.$data.'" AND manager_id IN ('.$arr .")");
        $this->db->query($query);
    }


    public function existingTask($number, $plus = false, $task_date = null){
        if ($task_date === null) {
            $task_date = date("Y-m-d");
        }

        $selectQuery = $this->db->placehold("Select id FROM __pr_tasks WHERE task_date = ? and number = ?", (string)$task_date, $number);
        $this->db->query($selectQuery);
        return $this->db->results();

    }


    public function get_pr_tasks($filter = array(),bool $plus = false)
    {
        $id_filter = '';
        $manager_id_filter = '';
        $task_date_from_border = '';
        $task_date_to_border = '';
        $task_date_filter = '';
        $period_filter = '';
        $status_filter = '';
        $close_filter = '';
        $prolongation_filter = '';
        $keyword_filter = '';
        $limit = 1000000;
        $page = 1;
        $sort = 'id DESC';
        $sort_by_mngr = '';
        $user_join = '';
        $ub_join = '';
        $search_filter = '';
        $order_by_manager = "";
        $select="";
        $organization_join = '';
        $organization_filter = '';

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND pr.id IN (?@)", array_map('intval', (array) $filter['id']));

        if (!empty($filter['manager_id'])){
            $manager_id_filter = $this->db->placehold("AND pr.manager_id IN (?@)", array_map('intval', (array) $filter['manager_id']));
            if(count($filter['manager_id']) > 1){
                /*при фильтре по нескольким менеджерам сначала сортируем по менеждерам, а внутри каждого уже по юзерскому значению */
                $sort_by_mngr = 'pr.manager_id ASC,';
            }
        }

        if (!empty($filter['task_date_from']))
            $task_date_from_border = $this->db->placehold("AND pr.task_date >= ?", $filter['task_date_from']);

        if (!empty($filter['task_date_to']))
            $task_date_to_border = $this->db->placehold("AND pr.task_date <= ?", $filter['task_date_to']);

        if (!empty($filter['task_date']))
            $task_date_filter = $this->db->placehold("AND pr.task_date = ?", $filter['task_date']);

        if (!empty($filter['status']))
            $status_filter = $this->db->placehold("AND pr.status IN (?@)", array_map('intval', (array) $filter['status']));

        if (!empty($filter['period'])) {
            if (is_array($filter['period'])) {
                $period_filter = $this->db->placehold(" AND pr.period IN(?@)", array_map('strval', (array) $filter['period']));
            } else {
                $period_filter = $this->db->placehold("AND pr.period = ?", $filter['period']);
            }
        }

        if (isset($filter['close']))
            $close_filter = $this->db->placehold("AND pr.close = ?", (int)$filter['close']);

        if (isset($filter['prolongation']))
            $prolongation_filter = $this->db->placehold("AND pr.prolongation = ?", (int)$filter['prolongation']);

        if(isset($filter['keyword']))
        {
            $keywords = explode(' ', $filter['keyword']);
            foreach($keywords as $keyword)
                $keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
        }

        if (!empty($filter['search']))
        {
            if (!empty($filter['search']['fio']))
            {
                $ub_join = 1;
                $search_filter .= $this->db->placehold(" AND ub.client LIKE '%".$this->db->escape($filter['search']['fio'])."%'");
            }

            if (!empty($filter['search']['phone']))
            {
                $user_join = 1;
                $search_filter .= $this->db->placehold(" AND u.phone_mobile LIKE '%".$this->db->escape(str_replace(array(' ', '-', '(', ')', '+'), '', $filter['search']['phone']))."%'");
            }

            if (!empty($filter['search']['number']))
            {
                $ub_join = 1;
                $search_filter .= $this->db->placehold(" AND ub.zaim_number LIKE '%".$this->db->escape($filter['search']['number'])."%'");
            }

            if (isset($filter['search']['manager']))
            {
                $search_filter .= $this->db->placehold(" AND pr.manager_id = ?", (int)$filter['search']['manager']);
            }

            if (isset($filter['search']['status']))
            {
                $search_filter .= $this->db->placehold(" AND pr.status = ?", (int)$filter['search']['status']);
            }
        }


        if (isset($filter['contact_center'])) {
            $contact_center = $filter['contact_center'];
            $order_by_manager = "CASE WHEN pr.manager_id = $contact_center THEN 0 ELSE 1 END,";
        }

        if (!empty($filter['organization_id'])) {
            $organization_join = "
                LEFT JOIN s_contracts AS c ON c.number = pr.number
                LEFT JOIN s_orders AS o ON o.id = c.order_id
                LEFT JOIN managers_schedule ON managers_schedule.manager_id = pr.manager_id
                    AND managers_schedule.date = pr.task_date
            ";
            $organization_filter = $this->db->placehold(" AND (o.organization_id = ? OR managers_schedule.organization_id = ?)", (int)$filter['organization_id'], (int)$filter['organization_id']);
            $ub_join = 1;
        }

        if(isset($filter['limit']))
            $limit = max(1, intval($filter['limit']));

        if(isset($filter['page']))
            $page = max(1, intval($filter['page']));

        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);
        
        if (!empty($filter['sort']))
        {
            switch ($filter['sort']):
                case 'fio_asc':
                    if ($plus) {
                        $sort = 'pr.marked Desc';
                    } else {
                        $user_join = 1;
                        $sort = 'u.lastname ASC';
                    }
                    break;

                case 'fio_desc':
                    if ($plus) {
                        $sort = 'pr.paid  Desc';
                    } else {
                        $user_join = 1;
                        $sort = 'u.lastname DESC';
                    }
                    break;

                case 'phone_asc':
                    $user_join = 1;
                    $sort = 'u.phone_mobile ASC';
                    break;

                case 'phone_desc':
                    $user_join = 1;
                    $sort = 'u.phone_mobile DESC';
                    break;

                case 'timezone_asc':
                    $sort = 'pr.timezone ASC';
                    break;

                case 'timezone_desc':
                    $sort = 'pr.timezone DESC';
                    break;

                case 'number_asc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_number ASC';
                    break;

                case 'number_desc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_number DESC';
                    break;

                case 'date_asc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_date ASC';
                    break;

                case 'date_desc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_date DESC';
                    break;

                case 'summ_asc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_summ ASC';
                    break;

                case 'summ_desc':
                    $ub_join = 1;
                    $sort = 'ub.zaim_summ DESC';
                    break;

                case 'payment_date_asc':
                    $ub_join = 1;
                    $sort = 'ub.payment_date ASC';
                    break;

                case 'payment_date_desc':
                    $ub_join = 1;
                    $sort = 'ub.payment_date DESC';
                    break;

                case 'payment_asc':
                    $ub_join = 1;
                    $sort = 'ub.ostatok_od ASC';
                    break;

                case 'payment_desc':
                    $ub_join = 1;
                    $sort = 'ub.ostatok_od DESC';
                    break;

                case 'prolongation_asc':
                    $ub_join = 1;
                    $sort = 'ub.prolongation_amount ASC';
                    break;

                case 'prolongation_desc':
                    $ub_join = 1;
                    $sort = 'ub.prolongation_amount DESC';
                    break;

                case 'manager_asc':
                    $sort = 'pr.manager_id ASC';
                    break;

                case 'manager_desc':
                    $sort = 'pr.manager_id DESC';
                    break;

                case 'status_asc':
                    $sort = 'pr.status ASC';
                    break;

                case 'status_desc':
                    $sort = 'pr.status DESC';
                    break;
                case 'count_asc':
                    $sort = 'status_count DESC';
                    break;
                case 'count_desc':
                    $sort = 'status_count ASC';
                    break;
            endswitch;
        }

        if (!empty($user_join))
            $user_join = "LEFT JOIN __users AS u ON u.id = pr.user_id";
        if (!empty($ub_join))
            $ub_join = "LEFT JOIN __user_balance AS ub ON ub.id = pr.user_balance_id";
        if (!empty($organization_join))
            $organization_join = trim($organization_join);
        if ($plus) {
            $start = date('Y-m-d', strtotime('-2 weeks'));
            $end = date('Y-m-d');
            $select = ',
                (Select count(id) from s_pr_tasks where (status = 3 or status = 1) And task_date BETWEEN "'.$start.'" and "'.$end.'" AND user_id = pr.user_id And  period IN("period_one_two") ) as status_count';
        }

        /*через SQL_CALC_FOUND_ROWS отдается число строк всегда без учета лимита и оффсета*/
        $query = $this->db->placehold("
            SELECT SQL_CALC_FOUND_ROWS
                pr.id,
                pr.number,
                pr.task_date,
                pr.ticketId,
                pr.user_id,
                pr.user_balance_id,
                pr.manager_id,
                pr.status,
                pr.close,
                pr.prolongation,
                pr.created,
                pr.od_start,
                pr.percents_start,
                pr.period,
                pr.paid,
                pr.timezone,
                pr.recall_date,
                pr.perspective_date,
                pr.marked,
                pr.vox_call,
                pr.sms_send
            $select
            FROM __pr_tasks AS pr
            $user_join
            $ub_join
            $organization_join
            WHERE 1
                $id_filter
                $manager_id_filter
				$task_date_from_border
				$task_date_to_border
                $task_date_filter
                $period_filter
                $status_filter
                $close_filter
                $prolongation_filter
                $keyword_filter
                $search_filter
                $organization_filter
            ORDER BY $order_by_manager $sort_by_mngr pr.status ASC, $sort
            $sql_limit
        ");

        $start = microtime(true);
        $this->db->query($query);
        $results = $this->db->results();
        $duration = microtime(true) - $start;

        logger('cc_task')->info('get_pr_tasks', [
            'duration'   => $duration,
            'sql'           => $query,
            'rows_returned' => count($results),
        ]);

        $this->db->query("SELECT FOUND_ROWS()");
        $total_cnt = $this->db->results();
//echo __FILE__.' '.__LINE__.'<br /><pre>';var_dump($query, $results);echo '</pre><hr />';

        return ["data" => $results, "total_count" => $total_cnt[0]->{"FOUND_ROWS()"}];
    }


    public function delete_vox_pr_task($phone)
    {
        $query = $this->db->placehold("
            DELETE __pr_tasks FROM __pr_tasks 
            LEFT JOIN s_users on  __pr_tasks.user_id =  s_users.id    
                   WHERE phone_mobile = ?
        ", (string) $phone);

        $this->db->query($query);
    }

    public function update_vox_pr_task($phone,$manager)
    {
        $query = $this->db->placehold("
            UPDATE __pr_tasks
            LEFT JOIN s_users ON __pr_tasks.user_id = s_users.id
            SET __pr_tasks.manager_id = ?
            WHERE s_users.phone_mobile = ?
            ", $manager, $phone);

        $this->db->query($query);

    }



    public function count_pr_tasks($filter = array())
    {
        $id_filter = '';
        $manager_id_filter = '';
        $task_date = '';
        $period_filter = '';
        $status_filter = '';
        $close_filter = '';
        $prolongation_filter = '';
        $keyword_filter = '';
        $search_filter = '';
        $organization_join = '';
        $organization_filter = '';

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND pr.id IN (?@)", array_map('intval', (array) $filter['id']));

        if (!empty($filter['manager_id']))
            $manager_id_filter = $this->db->placehold("AND pr.manager_id IN (?@)", array_map('intval', (array) $filter['manager_id']));

        if (!empty($filter['task_date']))
            $task_date = $this->db->placehold("AND pr.task_date = ?", $filter['task_date']);

        if (!empty($filter['status']))
            $status_filter = $this->db->placehold("AND pr.status IN (?@)", array_map('intval', (array) $filter['status']));

        if (!empty($filter['period']))
            $period_filter = $this->db->placehold("AND pr.period = ?", $filter['period']);

		if (isset($filter['close']))
            $close_filter = $this->db->placehold("AND pr.close = ?", (int)$filter['close']);

		if (isset($filter['prolongation']))
            $prolongation_filter = $this->db->placehold("AND pr.prolongation = ?", (int)$filter['prolongation']);

        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (!empty($filter['organization_id'])) {
            $organization_join = "
                LEFT JOIN s_contracts AS c ON c.number = pr.number
                LEFT JOIN s_orders AS o ON o.id = c.order_id
                LEFT JOIN managers_schedule ON managers_schedule.manager_id = pr.manager_id
                    AND managers_schedule.date = pr.task_date
            ";
            $ub_join = 1;
        }

        if (isset($filter['search']))
        {
            if (!empty($filter['search']['fio']))
            {
                $ub_join = 1;
                $search_filter .= $this->db->placehold(" AND ub.client LIKE '%".$this->db->escape($filter['search']['fio'])."%'");
            }

            if (!empty($filter['search']['phone']))
            {
                $user_join = 1;
                $search_filter .= $this->db->placehold(" AND u.phone_mobile LIKE '%".$this->db->escape(str_replace(array(' ', '-', '(', ')', '+'), '', $filter['search']['phone']))."%'");
            }

            if (!empty($filter['search']['number']))
            {
                $ub_join = 1;
                $search_filter .= $this->db->placehold(" AND ub.zaim_number LIKE '%".$this->db->escape($filter['search']['number'])."%'");
            }

            if (isset($filter['search']['manager']))
            {
                $search_filter .= $this->db->placehold(" AND pr.manager_id = ?", (int)$filter['search']['manager']);
            }

            if (isset($filter['search']['status']))
            {
                $search_filter .= $this->db->placehold(" AND pr.status = ?", (int)$filter['search']['status']);
            }
        }

        if (!empty($user_join))
            $user_join = "LEFT JOIN __users AS u ON u.id = pr.user_id";
        if (!empty($ub_join))
            $ub_join = "LEFT JOIN __user_balance AS ub ON ub.id = pr.user_balance_id";
        if (!empty($organization_join)) {
            $organization_join = trim($organization_join);
            $organization_filter = $this->db->placehold(" AND (o.organization_id = ? OR managers_schedule.organization_id = ?)", (int)$filter['organization_id'], (int)$filter['organization_id']);
        }


		$query = $this->db->placehold("
            SELECT COUNT(pr.id) AS count
            FROM __pr_tasks AS pr
            $user_join
            $ub_join
            $organization_join
            WHERE 1
                $id_filter
                $manager_id_filter
                $task_date
                $period_filter
                $status_filter
                $close_filter
                $prolongation_filter
                $keyword_filter
                $search_filter
                $organization_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');

        return $count;
    }

    public function add_pr_task($pr_task)
    {
        $query = $this->db->placehold("
            INSERT INTO __pr_tasks SET ?%
        ", (array) $pr_task);
        $this->db->query($query);
        $id = $this->db->insert_id();

        return $id;
    }

    public function update_pr_task($id, $pr_task)
    {
        $query = $this->db->placehold("
            UPDATE __pr_tasks SET ?% WHERE id = ?
        ", (array) $pr_task, (int) $id);
        $res = $this->db->query($query);
//echo __FILE__.' '.__LINE__.'<br /><pre>';var_dump($res, $query);echo '</pre><hr />';
        return $id;
    }

    public function delete_pr_task($id)
    {
        $query = $this->db->placehold("
            DELETE FROM __pr_tasks WHERE id = ?
        ", (int) $id);
        $this->db->query($query);
    }


	public function get_number_close_task($number)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __close_tasks
            WHERE number = ?
        ", (string)$number);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

	public function get_close_task($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __close_tasks
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }

	public function get_close_tasks($filter = array())
	{
		$id_filter = '';
		$pk_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND ct.id IN (?@)", array_map('intval', (array)$filter['id']));

		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (isset($filter['pk']))
            $pk_filter = $this->db->placehold("AND ct.pk = ?", (int)$filter['pk']);

        if (!empty($filter['sort']))
        {
            switch ($filter['sort']):

                case 'fio_asc':
                    $user_join = 1;
                    $sort = 'u.lastname ASC';
                    break;

                case 'fio_desc':
                    $user_join = 1;
                    $sort = 'u.lastname DESC';
                    break;

                case 'phone_asc':
                    $user_join = 1;
                    $sort = 'u.phone_mobile ASC';
                    break;

                case 'phone_desc':
                    $user_join = 1;
                    $sort = 'u.phone_mobile ASC';
                    break;

                case 'timezone_asc':
                    $sort = 'ct.timezone ASC';
                    break;

                case 'timezone_desc':
                    $sort = 'ct.timezone DESC';
                    break;

                case 'number_asc':
                    $ub_join = 1;
                    $sort = 'ct.number ASC';
                    break;

                case 'number_desc':
                    $ub_join = 1;
                    $sort = 'ct.number DESC';
                    break;

                case 'date_asc':
                    $ub_join = 1;
                    $sort = 'ct.close_date ASC';
                    break;

                case 'date_desc':
                    $ub_join = 1;
                    $sort = 'ct.close_date DESC';
                    break;

                case 'manager_asc':
                    $sort = 'ct.manager_id ASC';
                    break;

                case 'manager_desc':
                    $sort = 'ct.manager_id DESC';
                    break;

                case 'status_asc':
                    $sort = 'ct.status ASC';
                    break;

                case 'status_desc':
                    $sort = 'ct.status DESC';
                    break;

            endswitch;
        }

        if (!empty($user_join))
            $user_join = "LEFT JOIN __users AS u ON u.id = ct.user_id";

		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));

        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __close_tasks AS ct
            $user_join
            WHERE 1
                $id_filter
				$pk_filter
                $keyword_filter
            ORDER BY $sort 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();

        return $results;
	}

	public function count_close_tasks($filter = array())
	{
        $id_filter = '';
        $pk_filter = '';
        $keyword_filter = '';

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));

        if (isset($filter['pk']))
            $pk_filter = $this->db->placehold("AND pk = ?", (int)$filter['pk']);

        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __close_tasks
            WHERE 1
                $id_filter
                $pk_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
//echo __FILE__.' '.__LINE__.'<br /><pre>';var_dump($query);echo '</pre><hr />';
        return $count;
    }

    public function add_close_task($close_task)
    {
		$query = $this->db->placehold("
            INSERT INTO __close_tasks SET ?%
        ", (array)$close_task);
        $this->db->query($query);
        $id = $this->db->insert_id();

        return $id;
    }

    public function update_close_task($id, $close_task)
    {
		$query = $this->db->placehold("
            UPDATE __close_tasks SET ?% WHERE id = ?
        ", (array)$close_task, (int)$id);
        $this->db->query($query);

        return $id;
    }

    public function delete_close_task($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __close_tasks WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    public function getTasks($filter){

        $query = $this->db->placehold("
            SELECT phone_mobile FROM __pr_tasks
            left JOIN s_users on s_users.id = s_pr_tasks.user_id
            left Join s_user_balance on __pr_tasks.user_balance_id = s_user_balance.id
            WHERE __pr_tasks.manager_id = ?
            and  __pr_tasks.task_date = ?
            and ((close > 0)
            or (prolongation > 0) 
            or (s_user_balance.zaim_date = '0001-01-01T00:00:00') 
            or (s_user_balance.payment_date = '0001-01-01 00:00:00'))
        ", $filter['manager_id'],$filter['task_date']);
        $this->db->query($query);

        $result = $this->db->results('phone_mobile');
        return $result;
    }

    public function deleteTasks(array $numbers)
    {
        $data = date("Y-m-d");
        $numbers = implode(', ', $numbers);

        $query = $this->db->placehold("
            DELETE FROM s_pr_tasks
WHERE user_id IN (
    SELECT id
    FROM s_users
    WHERE phone_mobile IN (
       $numbers
    )
) AND task_date = ?
        ",$data);
        $this->db->query($query);
    }

    public function update_task_mark($phone)
    {
        $date = date("Y-m-d");
        $query = $this->db->placehold("
            SELECT id
                FROM __users
                WHERE phone_mobile = ? or work_phone = ? 
        ",(string)$phone,(string)$phone);

        $this->db->query($query);
        $result = $this->db->result('id');

        $query1 = $this->db->placehold("UPDATE s_pr_tasks
            SET marked = false
            WHERE task_date = ?
            AND user_id = ?
                ",$date,$result);
        $this->db->query($query1);
        return $result;
    }

    public function getVoxCall($zaimNumber)
    {
        $query = $this->db->placehold("
            SELECT EXISTS(SELECT *
                FROM s_pr_tasks
                WHERE number = ?  
                AND (status = 1 or status = 3) 
                AND period = 'period_one_two'
                ) as status
        ",(string)$zaimNumber);

        $this->db->query($query);
        return $this->db->result('status');
    }


    public function update_vox_call(int $user_id){
        $date = date("Y-m-d");
        $query = $this->db->placehold("UPDATE s_pr_tasks
            SET sms_send = true
            WHERE task_date = ?
            AND user_id = ?
                ",$date,$user_id);
        $this->db->query($query);

        $selectQuery = $this->db->placehold("
           SELECT sms_send FROM s_pr_tasks WHERE task_date = ? AND user_id = ?"
        ,$date,$user_id);

        $this->db->query($selectQuery);
        return $this->db->result('sms_send');
    }

    /**
     * @param int $user_id
     * @param int $status
     * @param bool $vox_call
     * @param string $date
     * @return void
     */
    public function updateTaskStatus(int $user_id, int $status,bool $vox_call, string $date)
    {
        $query = $this->db->placehold("UPDATE s_pr_tasks
        SET status = ?, vox_call = ? 
        WHERE task_date = ? AND user_id = ?
                ", $status,$vox_call, $date, $user_id);
        $this->db->query($query);
    }

    /**
     * @param $data
     * @return array|false
     */
    public function get_tasks($data)
    {
        $filter_manager = '';
        $filter_period = '';
        $filter_closed = '';
        $organization_join = '';
        $organization_filter = '';
        if (!empty($data['manager_id'])) {
            $filter_manager = $this->db->placehold("AND t.manager_id = ?", $data['manager_id']);
        }
        if (!empty($data['period'])) {
            $filter_period = $this->db->placehold("AND t.period = ?", $data['period']);
        }
        if (!empty($data['closed'])) {
            $filter_closed = $this->db->placehold("AND t.close = 0 AND t.prolongation = 0");
        }
        if (!empty($data['organization_id'])) {
            $organization_join = "
                LEFT JOIN s_contracts AS c ON c.number = t.number
                LEFT JOIN s_orders AS o ON o.id = c.order_id
            ";
            $organization_filter = $this->db->placehold(" AND o.organization_id = ?", (int)$data['organization_id']);
        }

        $query = $this->db->placehold("Select t.id,u.id as user_id,u.phone_mobile, t.timezone,u.lastname, u.firstname,u.patronymic,b.ostatok_od, b.ostatok_percents,b.ostatok_peni,b.prolongation_amount,b.zaim_date,b.payment_date,b.zayavka,b.zaim_number from __pr_tasks t
                                    JOIN __users u on t.user_id = u.id
                                    LEFT JOIN s_user_balance b on t.user_balance_id = b.id
                                    $organization_join
                                    WHERE 1  
                                    $filter_manager 
                                    $filter_period
                                    $filter_closed
                                    $organization_filter
                                    AND t.task_date BETWEEN ? AND ?
                                    ",
            $data['task_date_from'], $data['task_date_to']);

        $this->db->query($query);
        return $this->db->results();
    }

    public function getTaskWithPhone($phone)
    {
        $date = date("Y-m-d");
        $query = $this->db->placehold("
            SELECT 
                t.id, 
                t.number, 
                t.period, 
                t.user_id, 
                u.uid 
            FROM 
                s_pr_tasks t
            INNER JOIN 
                s_users u 
            ON 
                t.user_id = u.id
            WHERE 
                t.task_date = ? 
                AND u.phone_mobile = ?
", $date, $phone);
        $this->db->query($query);
        return $this->db->result();
    }
    public function getCallsBlacklistUsers($userId) {
        if (is_array($userId)) {
            $user_query = $this->db->placehold("user_id IN (?@)", $userId);
        } else {            
            $user_query = $this->db->placehold("user_id = ?", (int)$userId);
        }
        $query = $this->db->placehold("
            SELECT *  FROM calls_blacklist
            WHERE $user_query and deleted_at is null
        ");
        $this->db->query($query);
        if (is_array($userId)) {
            return $this->db->results();
        } else {
            return $this->db->result();
        }
    }

    public function exists() {
        $date = date("Y-m-d");
        $query = $this->db->placehold("SELECT *  FROM missed_calls                                                                                                        
                                          WHERE created = ?
                                         ", $date);
        $this->db->query($query);
        return $this->db->result();
    }

    /**
     * Проверяет, были ли уже отправлены недозвоны на сегодня для конкретной организации
     * @param int $organizationId
     * @return object|null
     */
    public function existsMissedCallsForOrganization($organizationId) {
        $date = date("Y-m-d");
        
        // Проверяем, есть ли поле organization_id в таблице
        $checkColumn = $this->db->placehold("SHOW COLUMNS FROM missed_calls LIKE 'organization_id'");
        $this->db->query($checkColumn);
        $columnExists = $this->db->result();
        
        if ($columnExists) {
            // Используем проверку по organization_id
            $query = $this->db->placehold("SELECT * FROM missed_calls 
                                              WHERE created = ? AND organization_id = ?
                                             ", $date, (int)$organizationId);
        } else {
            // Fallback: проверяем только по дате (старая логика)
            // Это не идеально, но работает если поле еще не добавлено
            $query = $this->db->placehold("SELECT * FROM missed_calls 
                                              WHERE created = ?
                                             ", $date);
        }
        
        $this->db->query($query);
        return $this->db->result();
    }

}
