<?php
/**
 * Extension for Simpla
 * File is autogenerated 04.03.2020 19:47:18 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Transactions extends Simpla
{
    /**
     * Статусы успешных транзакций
     */
    public const STATUSES_SUCCESS = ['CONFIRMED', 'AUTHORIZED'];

    /**
     * Тип оплаты для Кредитного рейтинга
     */
    public const PAYMENT_TYPE_CREDIT_RATING_FOR_NK = 'credit_rating_for_nk';
    public const PAYMENT_TYPE_CREDIT_RATING_AFTER_REJECTION = 'credit_rating_after_rejection';
    public const PAYMENT_TYPE_CREDIT_RATING_MAPPING = [
        1 => self::PAYMENT_TYPE_CREDIT_RATING_FOR_NK,
        2 => self::PAYMENT_TYPE_CREDIT_RATING_AFTER_REJECTION
    ];

	public function get_transaction($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __transactions
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_payment_id_transaction($payment_id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __transactions
            WHERE payment_id = ?
        ", (int)$payment_id);
        $this->db->query($query);
        $result = $this->db->result();
	
        return $result;
    }
    
	public function get_order_id_transaction($order_id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __transactions
            WHERE order_id = ?
        ", (string)$order_id);
        $this->db->query($query);
        $result = $this->db->result();

        return $result;
    }
    
	public function get_transactions($filter = array())
	{
		$id_filter = '';
        $order_id_filter = '';
        $user_id_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
        
        if (!empty($filter['user_id']))
            $user_id_filter = $this->db->placehold("AND user_id = ?", (int)$filter['user_id']);
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __transactions
            WHERE 1
                $id_filter
                $order_id_filter
                $user_id_filter
                $keyword_filter
            ORDER BY id DESC 
            $sql_limit
        ");
        $this->db->query($query);
        $results = $this->db->results();
        
        return $results;
	}
    
	public function count_transactions($filter = array())
	{
        $id_filter = '';
        $order_id_filter = '';
        $user_id_filter = '';
        $keyword_filter = '';
        $group_by = '';
        $select = [];

        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));

        if (!empty($filter['order_id']))
            $order_id_filter = $this->db->placehold("AND order_id = ?", (int)$filter['order_id']);
        
        if (!empty($filter['user_id']))
            $user_id_filter = $this->db->placehold("AND user_id = ?", (int)$filter['user_id']);
		
        if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('AND (name LIKE "%'.$this->db->escape(trim($keyword)).'%" )');
		}

        if (!empty($filter['filter_date_created'])) {
            $filter_created = $this->db->placehold("AND DATE(created) BETWEEN ? AND ?", $filter['filter_date_created']['filter_date_start'], $filter['filter_date_created']['filter_date_end']);
        } else {
            $filter_created = '';
        }

        if (!empty($filter['filter_payment_type'])) {
            $filter_payment_type = $this->db->placehold("AND payment_type = ?", trim($filter['filter_payment_type']));
        } else {
            $filter_payment_type = '';
        }

        if (!empty($filter['filter_statuses'])) {
            $filter_statuses = $this->db->placehold("AND status IN (?@)", $filter['filter_statuses']);
        } else {
            $filter_statuses = '';
        }

        if (!empty($filter['filter_group_by'])) {
            $group_by = "GROUP BY filter_date ASC";

            if ($filter['filter_group_by'] === 'day') {
                $select[] = ", DATE_FORMAT(created, '%Y.%m.%d') as filter_date";
            } elseif ($filter['filter_group_by'] === 'month') {
                $select[] = ", DATE_FORMAT(created, '%Y.%m') as filter_date";
            }
        }
                
		$query = $this->db->placehold("
            SELECT 
                COUNT(id) AS count
                -- {{select}}
            FROM __transactions
            WHERE 1
                $id_filter
                $order_id_filter
                $user_id_filter
                $keyword_filter
                $filter_created
                $filter_payment_type
                $filter_statuses
                -- {{group_by}}
        ");

        $query = strtr($query, [
            '-- {{select}}' => !empty($select) ? implode("\n", $select) : '',
            '-- {{group_by}}' => $group_by,
        ]);

        $this->db->query($query);

        if (!empty($filter['filter_group_by'])) {
            return $this->db->results();
        } else {
            return $this->db->result('count');
        }
    }

    /**
     * Получает общую сумму
     * @param array $filter_data
     * @return array|false|int
     */
    public function getTotalAmount(array $filter_data = [])
    {
        $group_by = '';
        $select = [];
        $where = [];

        if (!empty($filter_data['filter_date_created'])) {
            $where[] = $this->db->placehold("DATE(created) BETWEEN ? AND ?", $filter_data['filter_date_created']['filter_date_start'], $filter_data['filter_date_created']['filter_date_end']);
        }

        if (!empty($filter_data['filter_payment_type'])) {
            $where[] = $this->db->placehold("payment_type = ?", trim($filter_data['filter_payment_type']));
        }

        if (!empty($filter_data['filter_statuses'])) {
            $where[] = $this->db->placehold("status IN (?@)", $filter_data['filter_statuses']);
        }

        if (!empty($filter_data['filter_group_by'])) {
            $group_by = "GROUP BY filter_date ASC";

            if ($filter_data['filter_group_by'] === 'day') {
                $select[] = ", DATE_FORMAT(created, '%Y.%m.%d') as filter_date";
            } elseif ($filter_data['filter_group_by'] === 'month') {
                $select[] = ", DATE_FORMAT(created, '%Y.%m') as filter_date";
            }
        }

        $query = $this->db->placehold("
            SELECT 
                SUM(amount)/100 AS total_amount
                -- {{select}}
            FROM __transactions
            WHERE 1
                -- {{where}}
                -- {{group_by}}
        ");

        $query = strtr($query, [
            '-- {{select}}' => !empty($select) ? implode("\n", $select) : '',
            '-- {{where}}' => !empty($where) ? "AND " . implode(" AND ", $where) : '',
            '-- {{group_by}}' => $group_by,
        ]);

        $this->db->query($query);

        if (!empty($filter_data['filter_group_by'])) {
            return $this->db->results();
        } else {
            return $this->db->result('total_amount');
        }
    }
    
    public function add_transaction($transaction)
    {
		$query = $this->db->placehold("
            INSERT INTO __transactions SET ?%
        ", (array)$transaction);
        $this->db->query($query);
        $id = $this->db->insert_id();
        
        return $id;
    }
    
    public function update_transaction($id, $transaction)
    {
		$query = $this->db->placehold("
            UPDATE __transactions SET ?% WHERE id = ?
        ", (array)$transaction, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_transaction($id)
    {
		$query = $this->db->placehold("
            DELETE FROM __transactions WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    /**
     * Обновляет транзакции
     * @param array $ids
     * @param $transaction
     * @return void
     */
    public function update_transactions(array $ids, $transaction)
    {
        $query = $this->db->placehold("UPDATE __transactions SET ?% WHERE id IN(?@)", (array)$transaction, array_map('intval', $ids));
        $this->db->query($query);
    }
}