<?php
/**
 * Extension for Simpla
 * File is autogenerated 05.02.2021 8:47:52 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Verification extends Simpla
{
	
	public function get_all(){
		$this->db->query("SELECT * FROM `s_managers` WHERE `role` = 'verificator'");
        $results = $this->db->results();
		return $results;
	}
	
	public function get_one_by_date($id, $from = false, $to = false){
		if($from){
			if($to){
				$sql_piece = ' AND (date BETWEEN "'.$from.'" AND "'.$to.'")';
			}else{
				$sql_piece = ' AND (date BETWEEN "'.$from.'" AND "'.date("d.m.Y").'")';
			}
		}else{
			$sql_piece = '';
		}
		$this->db->query("
			SELECT 
				* 
			FROM 
				`s_orders` 
			WHERE 
				manager_id= '".$id."'".$sql_piece
		);
		$results = $this->db->results();
		return $results;
	}
	
	public function get_orders_count($from = false, $to = false){
		if($from){
			if($to){
				$sql_piece = ' WHERE (date BETWEEN "'.$from.'" AND "'.$to.'")';
			}else{
				$sql_piece = ' WHERE (date BETWEEN "'.$from.'" AND "'.date("d.m.Y").'")';
			}
		}else{
			$sql_piece = '';
		}
		$this->db->query("SELECT COUNT(*) as `counter` FROM `s_orders`".$sql_piece);
        $results = $this->db->results();
		return $results;
	}
	
	public function get_status_two_orders($id, $from = false, $to = false){
		if($from){
			if($to){
				$sql_piece = ' AND (date BETWEEN "'.$from.'" AND "'.$to.'")';
			}else{
				$sql_piece = ' AND (date BETWEEN "'.$from.'" AND "'.date("d.m.Y").'")';
			}
		}else{
			$sql_piece = '';
		}
		$this->db->query("SELECT COUNT(*) as `counter` FROM `s_orders` WHERE status='2' AND manager_id='".$id."'".$sql_piece);
        $results = $this->db->results();
		return $results;
	}
	
	public function get_average_time($id, $from = false, $to = false){
		if($from){
			if($to){
				$sql_piece = ' AND (verification_stats.dates BETWEEN "'.$from.'" AND "'.$to.'")';
			}else{
				$sql_piece = ' AND (verification_stats.dates BETWEEN "'.$from.'" AND "'.date("d.m.Y").'")';
			}
		}else{
			$sql_piece = '';
		}
		$this->db->query("
		SELECT 
			TIMEDIFF(verification_stats.dates, vs1.dates) as delta
		FROM 
			verification_stats
		LEFT JOIN
			verification_stats as `vs1` ON (
					vs1.manager_id='".$id."' 
				AND 
					vs1.order_id = verification_stats.order_id 
				AND 
					vs1.start_status != verification_stats.start_status
			)
		WHERE vs1.id != 'NULL'
		".$sql_piece);
        $results = $this->db->results();
		return $results;
	}
	
	public function get_defaults($id, $from = false, $to = false){
		if($from){
			if($to){
				$sql_piece = ' WHERE (s_orders.date BETWEEN "'.$from.'" AND "'.$to.'")';
			}else{
				$sql_piece = ' WHERE (s_orders.date BETWEEN "'.$from.'" AND "'.date("d.m.Y").'")';
			}
		}else{
			$sql_piece = '';
		}
		$this->db->query("
			SELECT 
				s_orders.id, s_orders.user_id, s_orders.amount, s_user_balance.last_prolongation
			FROM 
				s_orders 
			LEFT JOIN 
				s_user_balance ON (s_orders.user_id = s_user_balance.user_id)
			WHERE 
				s_orders.manager_id= '".$id."'
			AND
				s_user_balance.payment_date > cast(CURRENT_DATE() - 1 as date)
		".$sql_piece);
        $results = $this->db->results();
		return $results;
	}
	
}


?>