<?php
/**
 * Extension for Simpla
 * File is autogenerated 11.03.2020 21:24:52 by CRUD 
 * @author Ruslan Kopyl
 */
require_once 'Simpla.php';

class Docs extends Simpla
{
	public function get_doc($id)
	{
		$query = $this->db->placehold("
            SELECT * 
            FROM __docs
            WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
        if ($result = $this->db->result())
        {
            $result->filename_short = $this->create_short_filename($result->filename);
            $result->icon = $this->create_icon($result->filename);
        }
	
        return $result;
    }
    
	public function get_docs($filter = array())
	{
		$id_filter = '';
        $visible_filter = '';
        $in_info_filter = '';
        $in_register_filter = '';
        $keyword_filter = '';
        $limit = 1000;
		$page = 1;
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
        
        if (isset($filter['visible']))
            $visible_filter = $this->db->placehold("AND visible = ?", (int)$filter['visible']);
        
        if (isset($filter['in_info']))
            $in_info_filter = $this->db->placehold("AND in_info = ?", (int)$filter['in_info']);
        
        if (isset($filter['in_register']))
            $in_register_filter = $this->db->placehold("AND in_register = ?", (int)$filter['in_register']);
        
		if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('
                    AND (
                        name LIKE "%'.$this->db->escape(trim($keyword)).'%" 
                        OR description LIKE "%'.$this->db->escape(trim($keyword)).'%" 
                    )
                ');
		}
        
		if(isset($filter['limit']))
			$limit = max(1, intval($filter['limit']));

		if(isset($filter['page']))
			$page = max(1, intval($filter['page']));
            
        $sql_limit = $this->db->placehold(' LIMIT ?, ? ', ($page-1)*$limit, $limit);

        $query = $this->db->placehold("
            SELECT * 
            FROM __docs
            WHERE 1
                $id_filter
                $visible_filter
                $in_info_filter
                $in_register_filter
                $keyword_filter
            ORDER BY position ASC 
            $sql_limit
        ");
        $this->db->query($query);
        if ($results = $this->db->results())
        {
            foreach ($results as $result)
            {
                $result->filename_short = $this->create_short_filename($result->filename);
                $result->icon = $this->create_icon($result->filename);
            }
        }
        
        return $results;
	}
    
	public function count_docs($filter = array())
	{
        $id_filter = '';
        $visible_filter = '';
        $in_info_filter = '';
        $in_register_filter = '';
        $keyword_filter = '';
        
        if (!empty($filter['id']))
            $id_filter = $this->db->placehold("AND id IN (?@)", array_map('intval', (array)$filter['id']));
		
        if (isset($filter['visible']))
            $visible_filter = $this->db->placehold("AND visible = ?", (int)$filter['visible']);
        
        if (isset($filter['in_info']))
            $in_info_filter = $this->db->placehold("AND in_info = ?", (int)$filter['in_info']);
        
        if (isset($filter['in_register']))
            $in_register_filter = $this->db->placehold("AND in_register = ?", (int)$filter['in_register']);
        
       if(isset($filter['keyword']))
		{
			$keywords = explode(' ', $filter['keyword']);
			foreach($keywords as $keyword)
				$keyword_filter .= $this->db->placehold('
                    AND (
                        name LIKE "%'.$this->db->escape(trim($keyword)).'%" 
                        OR description LIKE "%'.$this->db->escape(trim($keyword)).'%" 
                    )
                ');
		}
                
		$query = $this->db->placehold("
            SELECT COUNT(id) AS count
            FROM __docs
            WHERE 1
                $id_filter
                $visible_filter
                $in_info_filter
                $in_register_filter
                $keyword_filter
        ");
        $this->db->query($query);
        $count = $this->db->result('count');
	
        return $count;
    }
    
    public function add_doc($doc)
    {
		$query = $this->db->placehold("
            INSERT INTO __docs SET ?%, created = NOW()
        ", (array)$doc);
        $this->db->query($query);
        $id = $this->db->insert_id();
//echo __FILE__.' '.__LINE__.'<br /><pre>';var_dump($query);echo '</pre><hr />';
        return $id;
    }
    
    public function update_doc($id, $doc)
    {
		$query = $this->db->placehold("
            UPDATE __docs SET ?% WHERE id = ?
        ", (array)$doc, (int)$id);
        $this->db->query($query);
        
        return $id;
    }
    
    public function delete_doc($id)
    {
		$this->delete_file($id);
        
        $query = $this->db->placehold("
            DELETE FROM __docs WHERE id = ?
        ", (int)$id);
        $this->db->query($query);
    }

    public function delete_file($doc_id)
    {
    	$query = $this->db->placehold("SELECT filename FROM __docs WHERE id = ?", (int)$doc_id);
        $this->db->query($query);
        
        if ($filename = $this->db->result('filename'))
            @unlink($this->config->root_dir.$this->config->docs_files_dir.$filename);
        
        $this->db->query("UPDATE __docs SET filename = '' WHERE id = ?", (int)$doc_id);
    }
    
    public function create_short_filename($filename)
    {
        $filename_short = '';
        
        $ext = pathinfo($filename, PATHINFO_EXTENSION);
        $basename = pathinfo($filename, PATHINFO_FILENAME);
        
        if (strlen($basename) < 28)
            return $filename;
        
        $filename_short = substr($basename, 0, 20);
        $filename_short .= '...';
        $filename_short .= substr($basename, -1, 3);
        $filename_short .= '.'.$ext;
        
    	return $filename_short;
    }
    
    public function create_icon($filename)
    {
    	$ext = pathinfo($filename, PATHINFO_EXTENSION);
        
        switch ($ext):
            
            case 'zip':
                return 'zip.png';
            break;
            
            case 'rar':
                return 'rar.png';
            break;
            
            case 'pdf':
                return 'pdf.png';
            break;
            
            case 'xls':
            case 'xlsx':
                return 'xls.png';
            break;
            
            case 'odt':
            case 'doc':
            case 'docx':
            case 'rtf':
                return 'doc.png';
            break;
            
            case 'txt':
            case 'csv':
                return 'txt.png';
            break;
            
            case 'png':
            case 'gif':
            case 'jpeg':
            case 'jpg':
                return 'jpg.png';
            break;
            
            default:
                return 'file.png';
            
        endswitch;
    }

    /**
     * Получает параметры для PDF документа АСП подписи
     * @param Object $user
     * @param string $sms_code
     * @return array
     */
    public static function getAspParamsByUser(Object $user, string $sms_code = ''): array
    {
        $short_name = $user->lastname . ' ' . mb_substr($user->firstname, 0, 1) . '. ' . mb_substr($user->patronymic, 0, 1) . '.';
        $registration_address = "{$user->Regindex} {$user->Regregion}, {$user->Regcity}, ".
            "{$user->Regstreet} ул, д. {$user->Reghousing}, кв. {$user->Regroom}";

        return [
            'short_name' => $short_name,
            'birth_date' => $user->birth,
            'passport_serial' => $user->passport_serial,
            'passport_issued' => $user->passport_issued,
            'passport_code' => $user->subdivision_code,
            'passport_date' => $user->passport_date,
            'registration_address' => $registration_address,
            'sms_code' => $sms_code,
        ];
    }

    /**
     * Формирует PDF с подписью АСП о частоте взаимодействия с пользователем
     * @param Object $user
     * @param string $zaim_number
     * @return void
     */
    public function get_asp_zaim_pdf(Object $user, string $zaim_number): void
    {
        foreach (self::getAspParamsByUser($user, $_SESSION['sms']) as $param => $value)
        {
            $this->design->assign($param, $value);
        }

        $tpl = $this->design->fetch('pdf/asp_zaim.tpl');

        $this->pdf->create(
            $tpl,
            'СОГЛАСИЕ СУБЪЕКТА НА ИНЫЕ СПОСОБЫ и ЧАСТОТУ ВЗАИМОДЕЙСТВИЯ',
            'asp_zaim_' . $zaim_number . '.pdf',true
        );
    }

    public function getMicroZaimParamsByUser(Object $user, float $loan_amount, bool $is_user_credit_doctor = false, string $asp = null): array
    {
        $full_name = $this->helpers::getFIO($user);
        $passport = $this->users::splitPassportSerial($user->passport_serial);
        $addressReg = $this->formatRegistrationAddress($user);

        return [
            'full_name' => $full_name,
            'lastname' => $user->lastname,
            'firstname' => $user->firstname,
            'patronymic' => $user->patronymic,
            'birth' => $user->birth,
            'birth_date' => $user->birth,
            'passport_serial' => $passport['serial'],
            'passport_number' => $passport['number'],
            'passport_date' => $user->passport_date,
            'passport_issued' => $user->passport_issued,
            // Ключи для шаблона soglasie_na_bki.tpl (без подчёркивания)
            'regindex' => $user->Regindex,
            'regregion' => $user->Regregion,
            'regcity' => $user->Regcity,
            'regstreet' => $user->Regstreet,
            'reghousing' => $user->Reghousing,
            'regroom' => $user->Regroom,
            // Ключи legacy (с подчёркиванием) для других шаблонов
            'reg_city' => $user->Regcity,
            'reg_street' => $user->Regstreet,
            'reg_housing' => $user->Reghousing,
            'reg_room' => $user->Regroom,
            'fakt_city' => $user->Faktcity,
            'fakt_street' => $user->Faktstreet,
            'fakt_housing' => $user->Fakthousing,
            'fakt_room' => $user->Faktroom,
            'phone_mobile' => $user->phone_mobile,
            'email' => $user->email,
            'loan_amount' => $loan_amount,
            'is_user_credit_doctor' => $is_user_credit_doctor,
            'asp' => $asp,
            'current_date' => date('d.m.Y'),
            'document_created' => date('d.m.Y'),
            'sign_date' => date('d.m.Y'),
            'addressReg' => $addressReg
        ];
    }

    /**
     * Возвращает данные для арбитражного соглашения
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param string|null $sign_date
     * @param int|null $crossOrganizationId
     * @return array
     * @throws Exception
     */
    public function getArbitrationAgreementParams(Object $user, int $order_id, ?string $sms = null, ?string $sign_date = null, ?int $crossOrganizationId = null): array
    {
        $order = $this->orders->get_order($order_id);
        $orgId = $crossOrganizationId ?: $order->organization_id;
        $organization = $this->organizations->get_organization($orgId);

        $loan_type = '';
        if ($order->loan_type === 'PDL') {
            $loan_type = 'микрозайма';
        } elseif ($order->loan_type === 'IL') {
            $loan_type = 'потребительского займа';
        }

        try {
            $user_balance = $this->users->get_user_balance_for_order($user->id, $order->id_1c);
        } catch (Exception $e) {
            $user_balance = null;
        }

        $user_fakt_address = "{$user->Faktindex} {$user->Faktregion}, {$user->Faktcity}, ".
            "{$user->Faktstreet} ул, д. {$user->Fakthousing}, кв. {$user->Faktroom}";
        $balance_zaim_date = $user_balance && !empty($user_balance->zaim_date) ? $user_balance->zaim_date : null;
        if (!$sign_date) {
            $sign_date = (in_array($balance_zaim_date, ['0001-01-01T00:00:00', '0001-01-01 00:00:00']) || empty($balance_zaim_date))
                ? date('Y-m-d H:i:s')
                : $balance_zaim_date;
        }

        $addressReg = $this->formatRegistrationAddress($user);

        // Get bank data from params JSON field (fallback to direct properties for backward compatibility)
        $params = $organization->params ?? [];
        $bankInn = $params['bank_inn'] ?? $organization->inn ?? '';
        $bankName = $params['bank_name'] ?? $organization->bank_name ?? ($organization->bank ? trim(explode(',', $organization->bank, 2)[1] ?? $organization->bank) : '');
        $bankAccount = $params['account'] ?? $organization->account ?? ($organization->bank ? trim(explode(',', $organization->bank, 2)[0] ?? '') : '');
        $postAddress = $params['post_address'] ?? $organization->post_address ?? $organization->address;

        $passport_split = $this->helpers::splitPassportSerialForDocuments($user->passport_serial);
        $passportSeries = $passport_split['serial'];
        $passportNumber = $passport_split['number'];

        $smsArbitrage = $this->sms->get_messages([
            'order_id' => $order->id,
            'type' => 'arbitrage',
            'limit' => 1
        ]);

        return [
            'full_name' => $this->helpers::getFIO($user),
            'short_name' => $this->helpers::getShortFIO($user),
            'fakt_address' => $user_fakt_address,
            'birth_place' => $user->birth_place,
            'birth_date' => $user->birth,
            'phone_mobile' => $user->phone_mobile,
            'email' => $user->email,
            'addressReg' => $addressReg ?: ($user->registration_address ?? ''),
            'passport_serial' => $user->passport_serial,
            'passport_issued' => $user->passport_issued,
            'passport_date' => $user->passport_date,
            'subdivision_code' => $user->subdivision_code,

            'organization_name' => $organization->name,
            'organization_short_name' => $organization->short_name,
            'organization_inn' => $organization->inn,
            'organization_kpp' => $organization->kpp ?? 771401001,
            'organization_ogrn' => $organization->ogrn,
            'organization_address' => $organization->address,
            'organization_address_post' => $postAddress,
            'organization_director' => $organization->director ?? 'Поздняковa С.В.',
            'organization_prefix' => $organization->contract_prefix,
            'organization_id' => $organization->id,
            'lenderPhone' => $organization->phone ?? '',
            'organization_phone' => $organization->phone ?? '',
            'lenderPostAddress' => $postAddress,
            'lenderKpp' => $organization->kpp ?? 771401001,
            'lenderBank' => $bankName,
            'lenderBankAccount' => $bankAccount,
            'organization_email' => $organization->email ?? '',

            'zaim_date' => $user_balance ? $user_balance->zaim_date : '',
            'sign_date' => !empty($smsArbitrage) ? $smsArbitrage[0]->created : $sign_date,
            'lenderBankInn' => $bankInn,
            'payment_date' => $user_balance && !empty($user_balance->payment_date) ? $user_balance->payment_date : date('Y-m-d'),
            'overdue_date' => (new DateTime($user_balance && !empty($user_balance->payment_date) ? $user_balance->payment_date : date('Y-m-d')))->modify('+1 day'),
            'zaim_number' => $user_balance ? $user_balance->zaim_number : '',
            'loan_type' => $loan_type,
            'accept_sms' => !empty($smsArbitrage) ? $smsArbitrage[0]->code : $sms ?? $order->accept_sms,
            'arbitratorPhone' => '+7 (912) 123-45-67',
            'arbiter_fio' => 'Мартьянова Дениса Анатольевича',
            'arbiter_inn' => '183309017023',
            'arbiter_address' => 'Россия, 426068, Удмуртская Республика, г. Ижевск, ул. Автозаводская, д.56, кв.14',
            'arbiter_email' => 'mda@rosmail.su',
            'order_signed' => $order->status_1c === '5.Выдан',
            'passportSeries' => $passportSeries,
            'passport_series' => $passportSeries,
            'passportNumber' => $passportNumber,
            'passport_number' => $passportNumber,
        ];
    }

    /**
     * Генерирует PDF файл арбитражного соглашения
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param bool $storeToDb
     * @param int|null $crossOrganizationId
     * @return bool
     * @throws Exception
     */
    public function getArbitrationAgreementPdf(Object $user, int $order_id, string $sms = null, bool $storeToDb = false, ?int $crossOrganizationId = null): bool
    {
        $params = $this->docs->getArbitrationAgreementParams($user, $order_id, $sms, null, $crossOrganizationId);

        if ($storeToDb) {
            return $this->documents->create_document([
                'order_id' => $order_id,
                'user_id' => $user->id,
                'contract_number' => $params['zaim_number'],
                'type' => Documents::ARBITRATION_AGREEMENT,
                'params' => $params,
            ]);
        }

        $this->createDocumentForType($params, Documents::ARBITRATION_AGREEMENT);

        return true;
    }

    /**
     * Получает параметры для соглашения об акцепте оферты АСП
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param string|null $sign_date
     * @param int|null $crossOrganizationId
     * @return array
     * @throws Exception
     */
    public function getAspAgreementParams(Object $user, int $order_id, ?string $sms = null, ?string $sign_date = null, ?int $crossOrganizationId = null): array
    {
        $order = $this->orders->get_order($order_id);
        $orgId = $crossOrganizationId ?: $order->organization_id;
        $organization = $this->organizations->get_organization($orgId);

        // Формируем адрес регистрации из отдельных полей
        $addressReg = $this->formatRegistrationAddress($user);

        // Путь к изображению подписи
        $signatureImagePath = $this->config->root_dir . 'design/boostra_mini_norm/html/pdf/i/signature_akvarius.png';

        // Конвертируем PNG в JPEG временно для TCPDF
        $signatureJpgPath = $this->config->root_dir . 'design/boostra_mini_norm/html/pdf/i/signature_akvarius_temp.jpg';

        if (file_exists($signatureImagePath)) {
            // Создаем JPG версию если её нет
            if (!file_exists($signatureJpgPath)) {
                if (extension_loaded('gd')) {
                    $image = imagecreatefrompng($signatureImagePath);
                    $white = imagecolorallocate($image, 255, 255, 255);
                    imagefill($image, 0, 0, $white);
                    imagejpeg($image, $signatureJpgPath, 90);
                    imagedestroy($image);
                }
            }
        }

        $finalImagePath = file_exists($signatureJpgPath) ? $signatureJpgPath : $signatureImagePath;

        $passport_split = $this->helpers::splitPassportSerialForDocuments($user->passport_serial);
        $passportSeries = $passport_split['serial'];
        $passportNumber = $passport_split['number'];
        try {
            $user_balance = $this->users->get_user_balance_for_order($user->id, $order->id_1c);
        } catch (Exception $e) {
            $user_balance = null;
        }

        $balance_zaim_date = $user_balance && !empty($user_balance->zaim_date) ? $user_balance->zaim_date : null;
        if (!$sign_date) {
            $sign_date = ($balance_zaim_date === '0001-01-01T00:00:00' || empty($balance_zaim_date))
                ? date('Y-m-d H:i:s')
                : $balance_zaim_date;
        }

        return [
            'orderDate' => $balance_zaim_date ?? date('Y-m-d H:i:s'),
            'orderNumber' => $order->id,
            'lenderName' => $organization->name ?? 'МКК Бустра',
            'lenderOgrn' => $organization->ogrn ?? '',
            'lenderFio' => 'Позднякова С.В.',
            'lenderSite' => $organization->site ?? 'lk.boostra.ru',
            'lenderAddressPost' => $organization->post_address ?? $organization->address ?? 'г. Москва',
            'lenderAddressReg' => $organization->address ?? 'г. Москва',
            'lenderEmail' => $organization->email ?? 'info@boostra.ru',
            'fio' => $this->helpers::getFIO($user),
            'passportSeries' => $passportSeries ?? '', // макросы через snake_case
            'passport_series' => $passportSeries ?? '',
            'passportNumber' => $passportNumber ?? '', // макросы через snake_case
            'passport_number' => $passportNumber ?? '',
            'passportDate' => $user->passport_date ?? '',
            'passportPlace' => $user->passport_issued ?? '',
            'passportCode' => $user->subdivision_code ?? '',
            'addressReg' => $addressReg ?: ($user->registration_address ?? ''),
            'phone' => $user->phone_mobile ?? '',
            'email' => $user->email ?? '',
            'birthDate' => $user->birth ?? '',
            'plaintiffName' => 'ООО "ПКО ПЗ"',
            'organization_prefix' => $organization->contract_prefix,
            'organization_id' => $organization->id,
            'plaintiffSite' => 'pkopz.ru',
            'accept_sms' => $sms ?? $order->accept_sms,
            'sign_date' => $sign_date,
            'signature_image_path' => $finalImagePath,
            'order_signed' => $order->status_1c === '5.Выдан',
            'full_name' => $this->helpers::getFIO($user),
            'birth_date' => $user->birth,
            'organization_name' => $organization->name,
            'organization_director' => $organization->director ?? 'Поздняковa С.В.',
        ];
    }

    /**
     * Создает PDF документ соглашения АСП
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param bool $storeToDb
     * @param int|null $crossOrganizationId
     * @return bool
     */
    public function getAspAgreementPdf(Object $user, int $order_id, string $sms = null, bool $storeToDb = false, ?int $crossOrganizationId = null): bool
    {
        $params = $this->getAspAgreementParams($user, $order_id, $sms, null, $crossOrganizationId);
        $order = $this->orders->get_order($order_id);
        $tpl = ($params['organization_id'] ?? -1) == $this->organizations::FASTFINANCE_ID ? Documents::ASP_AGREEMENT_FASTFINANCE : Documents::ASP_AGREEMENT;

        if ($storeToDb) {
            return $this->documents->create_document([
                'order_id' => $order_id,
                'user_id' => $user->id,
                'contract_number' => $order->id,
                'type' => $tpl,
                'params' => $params,
            ]);
        }

        $this->createDocumentForType($params, $tpl);

        return true;
    }

    /**
     * Подготавливает шаблон, заголовок и имя файла для документа на основе переданных параметров и типа
     *
     * @param array $params Параметры для шаблона
     * @param string $type Тип документа
     * @return array
     */
    public function prepareDocumentData(array $params, string $type): array
    {
        $this->design->assignBulk($params);

        $contractParams = $this->documents->get_document_params();
        $tplName = $contractParams[$type][Documents::KEY_TEMPLATE];
        $title = $contractParams[$type][Documents::KEY_NAME];

        $tpl = $this->design->fetch('pdf/' . $tplName);

        return [
            'template' => $tpl,
            'title'    => $title,
            'filename' => $tplName
        ];
    }

    /**
     * Создаёт PDF-документ из шаблона.
     *
     * @param array $params Данные для шаблона
     * @param string $type Тип документа
     * @param string|null $filename Имя файла (если сохраняется)
     * @param string|null $path Путь сохранения
     * @param bool $save Сохранять ли файл
     * @return void
     */
    public function createDocumentForType(array $params, string $type, ?string $filename = null, ?string $path = null, bool $save = false): void
    {
        $this->organizations->assign_to_design();
        $doc = $this->prepareDocumentData($params, $type);

        $this->pdf->create(
            $doc['template'],
            $doc['title'],
            $filename ?? $doc['filename'],
            $save,
            ['path' => $path]
        );
    }

    /**
     * Генерирует PDF-документ во временный файл, возвращает его бинарное содержимое.
     *
     * @param string $contractNumber Номер договора
     * @param string $type Тип документа
     * @return string Путь к PDF-файлу
     * @throws Exception При ошибке чтения или сериализации
     */
    public function generateDocumentPdfToFile(string $contractNumber, string $type): string
    {
        $rawParams = $this->documents->getDocument($type, $contractNumber)->params;

        $params = unserialize($rawParams);

        $doc = $this->prepareDocumentData((array) $params, $type);

        $fileName = uniqid('doc_') . '.pdf';
        $customPath = dirname(__DIR__) . '/files/extras_documents';

        $this->pdf->create($doc['template'], $doc['title'], $fileName, true, ['path' => $customPath]);
        $this->pdf->reset();

        return rtrim($customPath, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $fileName;
    }


    /**
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param string|null $sign_date
     * @param int|null $crossOrganizationId
     * @return array
     */
    public function getOfferAgreementParams(Object $user, int $order_id, ?string $sms = null, ?string $sign_date = null, ?int $crossOrganizationId = null): array
    {
        $order = $this->orders->get_order($order_id);
        $orgId = $crossOrganizationId ?: $order->organization_id;
        $organization = $this->organizations->get_organization($orgId);

        // Адрес регистрации заемщика
        $addressReg = trim(sprintf(
            '%s %s, %s, ул. %s, д. %s, кв. %s',
            $user->Regindex,
            $user->Regregion,
            $user->Regcity,
            $user->Regstreet,
            $user->Reghousing,
            $user->Regroom
        ));

        $user_passport_split = $this->helpers::splitPassportSerial($user->passport_serial);
        try {
            $user_balance = $this->users->get_user_balance_for_order($user->id, $order->id_1c);
        } catch (Exception $e) {
            $user_balance = null;
        }

        if (!$sign_date) {
            $sign_date = $user_balance->zaim_date === '0001-01-01T00:00:00' ? date('Y-m-d H:i:s')
                : $user_balance->zaim_date;
        }

        return [
            'full_name' => $this->helpers::getFIO($user),
            'email' => $user->email,
            'phone' => $user->phone_mobile,
            'passport_serial' => $user_passport_split['serial'],
            'passport_number' => $user_passport_split['number'],
            'passport_date' => $user->passport_date,
            'passport_issued' => $user->passport_issued,
            'subdivision_code' => $user->subdivision_code,
            'registration_address' => $addressReg,
            'organization_name' => $organization->name,
            'organization_ogrn' => $organization->ogrn,
            'zaim_number' => $user_balance->zaim_number,
            'zaim_date' => $user_balance->zaim_date,
            'organization_site' => $organization->site,
            'organization_address_post' => $organization->address, //Почтовый
            'organization_director' => $organization->director ?? 'Поздняковa С.В.',
            'organization_address_req' => $organization->address, //Регистрации
            'organization_email' => $organization->email,
            'plaintiff_name' => 'ООО ПКО "ПРАВОВАЯ ЗАЩИТА"',
            'plaintiff_site' => 'https://pravza.com/',
            'accept_sms' => $sms ?? $order->accept_sms,
            'order_signed' => $order->status_1c === '5.Выдан',
            'organization_id' => $organization->id,
            'sign_date' => $sign_date,
        ];
    }

    /**
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param bool $storeToDb
     * @param int|null $crossOrganizationId
     * @return bool
     */
    public function getOfferAgreementPdf(Object $user, int $order_id, string  $sms = null, bool $storeToDb = false, ?int $crossOrganizationId = null): bool
    {
        $params = $this->getOfferAgreementParams($user, $order_id, $sms, null, $crossOrganizationId);
        if ($storeToDb) {
            return $this->documents->create_document([
                'order_id' => $order_id,
                'user_id' => $user->id,
                'contract_number' => $params['zaim_number'],
                'type' => Documents::OFFER_AGREEMENT,
                'params' => $params,
            ]);
        }

        $this->createDocumentForType($params, Documents::OFFER_AGREEMENT);

        return true;
    }


    /**
     * Возвращает параметры для документа
     * "Оферта о заключении арбитражного соглашения от цессионария"
     *
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param string|null $sign_date
     * @param string|null $sms_date
     * @param int|null $crossOrganizationId
     * @return array
     * @throws Exception
     */
    public function getOfferArbitrationCessionaryParams(Object $user, int $order_id, ?string $sms = null, ?string $sign_date = null, ?string $sms_date = null, ?int $crossOrganizationId = null): array
    {
        $order = $this->orders->get_order($order_id);
        $orgId = $crossOrganizationId ?: $order->organization_id;
        $organization = $this->organizations->get_organization($orgId);

        // Адрес регистрации заемщика
        $addressReg = trim(sprintf(
            '%s %s, %s, ул. %s, д. %s, кв. %s',
            $user->Regindex,
            $user->Regregion,
            $user->Regcity,
            $user->Regstreet,
            $user->Reghousing,
            $user->Regroom
        ));

        try {
            $user_balance = $this->users->get_user_balance_for_order($user->id, $order->id_1c);
        } catch (Exception $e) {
            $user_balance = null;
        }

        $passport_split = $this->helpers::splitPassportSerialForDocuments($user->passport_serial);
        $passportSeries = $passport_split['serial'];
        $passportNumber = $passport_split['number'];

        $smsArbitrage = $this->sms->get_messages([
            'order_id' => $order->id,
            'type' => 'arbitrage',
            'limit' => 1
        ]);

        return [
            'full_name' => $this->helpers::getFIO($user),
            'birth_date' => $user->birth,
            'birth_place' => $user->birth_place,
            'passport_serial' => $passportSeries,
            'passport_number' => $passportNumber,
            'passport_date' => $user->passport_date,
            'passport_issued' => $user->passport_issued,
            'subdivision_code' => $user->subdivision_code,
            'registration_address' => $addressReg,
            'phone_mobile' => $user->phone_mobile,
            'email' => $user->email,
            'organization_id' => $organization->id,
            'organization_name' => $organization->name ?? 'ООО «ПКО ПЗ»',
            'organization_short_name' => $organization->short_name,
            'organization_inn' => $organization->inn ?? '',
            'organization_ogrn' => $organization->ogrn ?? '',
            'organization_address' => $organization->address ?? '',
            'organization_director' => $organization->director ?? 'Поздняковa С.В.',
            'zaim_number' => $user_balance->zaim_number,
            'zaim_date' => $user_balance->zaim_date ?? '',
            'sign_date' => $sign_date ?? date('d.m.Y'),
            'sms_date' => !empty($smsArbitrage) ? $smsArbitrage[0]->created : $sms_date ?? $sign_date ?? date('d.m.Y H:i:s'),
            'accept_sms' => $sms ?? '',
            'order_signed' => $order->status_1c === '5.Выдан',
            'lenderEmail' => $organization->email ?? 'info@boostra.ru',
        ];
    }

    /**
     * Генерирует PDF "Оферта о заключении арбитражного соглашения от цессионария"
     *
     * @param Object $user
     * @param int $order_id
     * @param string|null $sms
     * @param bool $storeToDb
     * @param int|null $crossOrganizationId
     * @return bool
     * @throws Exception
     */
    public function getOfferArbitrationCessionaryPdf(Object $user, int $order_id, string $sms = null, bool $storeToDb = false, ?int $crossOrganizationId = null): bool
    {
        $params = $this->getOfferArbitrationCessionaryParams($user, $order_id, $sms, null, null, $crossOrganizationId);

        if ($storeToDb) {
            return $this->documents->create_document([
                'order_id' => $order_id,
                'user_id' => $user->id,
                'contract_number' => $params['zaim_number'],
                'type' => Documents::OFFER_ARBITRATION_CESSIONARY,
                'params' => $params,
            ]);
        }

        $this->createDocumentForType($params, Documents::OFFER_ARBITRATION_CESSIONARY);

        return true;
    }

    public function getBkiAgreementParams(object $user, ?object $order = null): array
    {
        $passport_split = $this->helpers::splitPassportSerialForDocuments($user->passport_serial);

        $addressReg = $this->formatRegistrationAddress($user);

        $params = [
            'full_name' => "{$user->lastname} {$user->firstname} {$user->patronymic}",
            'birth'                => $user->birth,
            'passport_serial'      => $passport_split['serial'],
            'passport_number'      => $passport_split['number'],
            'passport_date'        => $user->passport_date,
            'passport_issued'      => $user->passport_issued,
            'subdivision_code'     => $user->subdivision_code,
            'birth_place'          => $user->birth_place,
            'registration_address' => $addressReg,
        ];

        /**
         * Данные организации — только если есть $order
         */
        if ($order !== null) {
            $organization = $this->organizations->get_organization($order->organization_id);

            if ($organization) {
                $params['organization_name']    = $organization->name ?? '';
                $params['organization_inn']     = $organization->inn ?? '';
                $params['organization_ogrn']    = $organization->ogrn ?? '';
                $params['organization_address'] = $organization->address ?? '';
            }

            /**
             * Доп. данные — только если есть история займов
             */
            if (!empty($user->loan_history) && count($user->loan_history) > 0) {
                $params['accept_sms'] = $order->accept_sms ?? null;
                $params['sign_date']  = $order->accept_date ?? null;
                $params['user_inn']   = $user->inn ?? null;
                $params['user_snils'] = $user->Snils ?? null;
            }
        }

        return $params;
    }

    /**
     * Формирует адрес регистрации пользователя из отдельных полей
     * @param Object $user
     * @return string
     */
    private function formatRegistrationAddress(Object $user): string
    {
        $parts = [];
        if (!empty($user->Regindex))   $parts[] = $user->Regindex;
        if (!empty($user->Regregion))  $parts[] = $user->Regregion;
        if (!empty($user->Regcity))    $parts[] = $user->Regcity;
        if (!empty($user->Regstreet))  $parts[] = 'ул. ' . $user->Regstreet;
        if (!empty($user->Reghousing)) $parts[] = 'д. ' . $user->Reghousing;
        if (!empty($user->Regroom))    $parts[] = 'кв. ' . $user->Regroom;

        return implode(', ', $parts);
    }
}
